import { defineFlow } from "../flow.js";

export default defineFlow({
  name: "status-healthy",
  status: "pass",
  machines: [{ name: "a", enrolled: true }],
  steps: [
    { on: "a", guest: "printf 'healthy fixture\\n' > README.md" },
    { on: "a", tui: "setup" },
    { on: "a", waitFor: /What do you want to track here\?/ },
    { on: "a", keys: ["Enter"] },
    { on: "a", waitFor: /Which directory should rbox sync\?/ },
    { on: "a", keys: ["Enter"] },
    { on: "a", waitFor: /Workspace name \(Enter accepts,[\s\S]*for none\)/ },
    { on: "a", keys: ["Enter"] },
    { on: "a", waitFor: /How should rbox handle gitignored files\?/ },
    { on: "a", keys: ["Enter"] },
    { on: "a", waitFor: /Keep this workspace syncing in the background\?/, timeout: 120 },
    { on: "a", keys: ["Down", "Enter"] },
    { on: "a", pollUntil: { exec: ["status"], pattern: /^a · syncing normally$/m, timeout: 120 } },
    {
      on: "a",
      exec: ["status"],
      assertStdout: [/^a · syncing normally$/m, /^Signed in(?: as .+)? · solo$/m],
      assertNotStdout: [
        /background sync:/,
        /locking:/,
        /git-sync:/,
        /sync metrics:/,
        /commit-409/,
        /\d+ syncs/,
        /\b(?:ws|dev|acct)_[A-Za-z0-9_-]+\b/,
        /^\s*device\s+/m,
        /files on disk/,
        /sequence\s+\d+/,
      ],
      expectExit: 0,
    },
  ],
});
