import { expect, test } from "bun:test";
import * as daemonControl from "./daemon-control.js";
import type {
  DaemonBindingRecord,
  DaemonLiveObservation,
  DaemonLogSources,
  DaemonModeIntent,
  DaemonModeWitness,
  DaemonPidRecord,
  LogsDeps,
  LogsOptions,
  ParsedDaemonBinding,
  ParsedDaemonPid,
  StartDaemonOptions,
  StartDaemonResult,
  StopDaemonDeps,
} from "./daemon-control.js";

export type DaemonControlFacadeTypes = [
  DaemonBindingRecord,
  DaemonLiveObservation,
  DaemonLogSources,
  DaemonModeIntent,
  DaemonModeWitness,
  DaemonPidRecord,
  LogsDeps,
  LogsOptions,
  ParsedDaemonBinding,
  ParsedDaemonPid,
  StartDaemonOptions,
  StartDaemonResult,
  StopDaemonDeps,
];

test("daemon-control preserves its exact runtime compatibility surface", () => {
  expect(Object.keys(daemonControl).sort()).toEqual([
    "DAEMON_BOOT_ID_ENV",
    "DAEMON_HEARTBEAT_FUTURE_SKEW_MS",
    "DAEMON_MODE_WITNESS_TIMEOUT_MS",
    "DEFAULT_LOG_LINES",
    "admitLiveDaemonMode",
    "currentWorkspaceId",
    "daemonBindingStatus",
    "daemonBoundPath",
    "daemonCrashLogPath",
    "daemonPidPath",
    "daemonProcessMatches",
    "daemonRuntimeDir",
    "daemonSpawnArgs",
    "daemonStatusPath",
    "daemonVersionSkewLine",
    "forceKill",
    "formatDaemonProcessLabel",
    "guardDaemonCrashLog",
    "isDaemonProcess",
    "isDaemonRunning",
    "logsDaemon",
    "parseDaemonBinding",
    "parseDaemonPid",
    "readDaemonBinding",
    "readDaemonBindingRecord",
    "readDaemonModeWitness",
    "readDaemonPidRecord",
    "readMergedDaemonLogTail",
    "recordDaemonBinding",
    "removeDaemonRuntime",
    "resolveDaemonLogSources",
    "startDaemon",
    "stopDaemon",
    "waitForDaemonModeWitness",
    "waitForExit",
    "workspaceKey",
  ]);
});
