import {afterEach,beforeEach,describe,expect,test} from "bun:test";import fs from "node:fs/promises";import os from "node:os";import path from "node:path";
import {bootstrapAccount,phraseToRk,sha256Hex,utf8} from "../engine/e2ee/index.js";import type {GenesisAccountObservation,GenesisPresence} from "./e2ee-remote.js";import {saveDevice} from "./e2ee-keystore.js";import {publishGenesisJournal,stageRecoveryKey,type GenesisJournal} from "./genesis-durable.js";import {classifyEnrollment} from "./genesis-enrollment.js";
const ACCOUNT="acct_0123456789abcdef",DEVICE="dev_genesis",ZERO:GenesisPresence={rosters:0,keyStates:0,devices:0,workspaces:0,workspaceKeys:0,e2eePairingTokens:0};let home:string;
beforeEach(async()=>{home=await fs.mkdtemp(path.join(os.tmpdir(),"rbox-genesis-classifier-"));process.env.RBOX_HOME=home;});afterEach(async()=>{delete process.env.RBOX_HOME;await fs.rm(home,{recursive:true,force:true});});
const absent=(present:GenesisPresence=ZERO):GenesisAccountObservation=>({genesisPresenceVersion:1,claim:null,present});
async function complete(){const boot=await bootstrapAccount(ACCOUNT,DEVICE,1_900_000_000_000),present={...ZERO,rosters:1,keyStates:1,devices:1};const claim={genesisPresenceVersion:1 as const,recoveryWrap:JSON.stringify(boot.upload.recoveryWrap),recoveryWrapId:boot.upload.recoveryWrapId,claimCreatedAt:1_900_000_000_000,genesisDeviceId:DEVICE,rosters:[JSON.stringify(boot.upload.genesisRoster)],keyStates:[JSON.stringify(boot.upload.genesisKeyState)],devices:[{deviceId:DEVICE,sigPubkey:boot.upload.device.sigPubKey,encPubkey:boot.upload.device.encPubKey,mkWrap:JSON.stringify(boot.upload.device.mkWrap)}],present,repairTombstone:null};return{boot,observation:{genesisPresenceVersion:1 as const,claim,present,repairTombstone:null} satisfies GenesisAccountObservation};}
describe("design 180 enrollment classifier",()=>{
  test("only absent/all-zero/no-local is pristine",async()=>{expect((await classifyEnrollment(ACCOUNT,absent())).kind).toBe("pristine");for(const key of Object.keys(ZERO) as Array<keyof GenesisPresence>){expect((await classifyEnrollment(ACCOUNT,absent({...ZERO,[key]:1}))).kind).toBe("integrity-failure");}});
  test("exact all-zero tombstone is repair-ready and workspace-bearing is fatal",async()=>{const tomb=(workspaces:number):GenesisAccountObservation=>{const present={...ZERO,workspaces};const claim={genesisPresenceVersion:1 as const,recoveryWrap:"rbox:genesis-repair-tombstone:v1",recoveryWrapId:"rbox:genesis-repair-tombstone:v1",claimCreatedAt:1,genesisDeviceId:null,rosters:[],keyStates:[],devices:[],present,repairTombstone:{version:1 as const,repairId:"gra_"+"a".repeat(32),repairedAt:2}};return{genesisPresenceVersion:1,claim,present,repairTombstone:claim.repairTombstone};};expect((await classifyEnrollment(ACCOUNT,tomb(0))).kind).toBe("repair-ready");expect((await classifyEnrollment(ACCOUNT,tomb(1))).kind).toBe("integrity-failure");});
  test("fully verified no-journal account is enrolled",async()=>{expect((await classifyEnrollment(ACCOUNT,(await complete()).observation)).kind).toBe("enrolled");});
  test("exact journal fields classify committed-this-attempt; one request-field mismatch competes",async()=>{const {boot,observation}=await complete();await saveDevice(boot.secrets);await stageRecoveryKey(ACCOUNT,await phraseToRk(boot.recoveryPhrase));const request={recoveryWrap:JSON.stringify(boot.upload.recoveryWrap),recoveryWrapId:boot.upload.recoveryWrapId,genesisRoster:JSON.stringify(boot.upload.genesisRoster),genesisKeyState:JSON.stringify(boot.upload.genesisKeyState),device:{deviceId:DEVICE,sigPubKey:boot.upload.device.sigPubKey,encPubKey:boot.upload.device.encPubKey,mkWrap:JSON.stringify(boot.upload.device.mkWrap)}};const makeJournal=async(requestBody:string):Promise<GenesisJournal>=>({version:1,accountId:ACCOUNT,deviceId:DEVICE,startedAt:"2026-07-22T12:00:00.000Z",phase:"active",requestBody,requestSha256:await sha256Hex(utf8(requestBody)),originalCacheRecovery:false,completionHolds:["recovery-kit-staging"],completionReceipts:{}});const exact=await makeJournal(JSON.stringify(request));await publishGenesisJournal(exact);expect((await classifyEnrollment(ACCOUNT,observation)).kind).toBe("committed-this-attempt");const mismatch=await makeJournal(JSON.stringify({...request,device:{...request.device,sigPubKey:"different"}}));await publishGenesisJournal(mismatch);expect((await classifyEnrollment(ACCOUNT,observation)).kind).toBe("competing-genesis");});
});
