import {afterEach,beforeEach,describe,expect,test} from "bun:test";
import fs from "node:fs/promises";import os from "node:os";import path from "node:path";
import {canonicalString,generateRecoveryKey,sha256Hex,utf8} from "../engine/e2ee/index.js";
import {genesisPaths,hardenedWrite,loadStagedRecoveryKey,parseCompletionIntent,parseGenesisJournal,parsePrepublishMarker,publishCompletionIntent,publishGenesisJournal,publishPrepublishMarker,reconcileRetargetIntent,retargetCompletionIntent,stageRecoveryKey,type CompletionIntent,type GenesisJournal} from "./genesis-durable.js";

const ACCOUNT="acct_0123456789abcdef";let home:string;
beforeEach(async()=>{home=await fs.mkdtemp(path.join(os.tmpdir(),"rbox-genesis-durable-"));process.env.RBOX_HOME=home;});afterEach(async()=>{delete process.env.RBOX_HOME;await fs.rm(home,{recursive:true,force:true});});
async function journal():Promise<GenesisJournal>{const requestBody='{"recoveryWrap":"\\u0061","device":{"deviceId":"dev_a"}}';return{version:1,accountId:ACCOUNT,deviceId:"dev_a",startedAt:"2026-07-22T12:00:00.000Z",phase:"active",requestBody,requestSha256:await sha256Hex(utf8(requestBody)),originalCacheRecovery:false,completionHolds:["recovery-kit-staging"],completionReceipts:{}};}

describe("design 180 durable genesis artifacts",()=>{
  test("marker and journal parsers are strict and preserve exact request UTF-8",async()=>{const marker={version:1 as const,accountId:ACCOUNT,deviceId:"dev_a",repairId:null,startedAt:"2026-07-22T12:00:00.000Z",phase:"prepublish" as const};await publishPrepublishMarker(marker);expect(parsePrepublishMarker(await fs.readFile(genesisPaths(ACCOUNT).marker,"utf8"),ACCOUNT)).toEqual(marker);expect(()=>parsePrepublishMarker(canonicalString({...marker,extra:true}),ACCOUNT)).toThrow();const j=await journal();await publishGenesisJournal(j);expect((await parseGenesisJournal(await fs.readFile(genesisPaths(ACCOUNT).journal,"utf8"),ACCOUNT)).requestBody).toBe(j.requestBody);await expect(parseGenesisJournal(canonicalString({...j,requestSha256:"0".repeat(64)}),ACCOUNT)).rejects.toThrow();});
  test("staged RK is 0600 and phrase-round-trippable",async()=>{const rk=generateRecoveryKey();await stageRecoveryKey(ACCOUNT,rk);expect(await loadStagedRecoveryKey(ACCOUNT)).toEqual(rk);expect((await fs.stat(genesisPaths(ACCOUNT).stagedRk)).mode&0o777).toBe(0o600);});
  test("hardened writer awaits and fail-closes at every durability stage",async()=>{const stages=["ancestor-mkdir","ancestor-fsync","temp-create","temp-write","temp-fsync","temp-close","rename","read-back","published-file-fsync","parent-fsync"] as const;const seen:string[]=[];await hardenedWrite(path.join(genesisPaths(ACCOUNT).dir,"probe"),"bytes",{onStep:(step)=>{seen.push(step);}});expect(seen).toEqual(stages);for(const fail of stages){await expect(hardenedWrite(path.join(genesisPaths(ACCOUNT).dir,`fail-${fail}`),"x",{onStep:(step)=>{if(step===fail)throw new Error(fail);}})).rejects.toThrow(fail);}});
  test("completion intent binds exact account/digest and absence is distinguishable",async()=>{const j=await journal(),intent:CompletionIntent={version:1,accountId:ACCOUNT,requestSha256:j.requestSha256,mode:"kit-path",path:path.resolve(home,"kit.txt"),intentAt:"2026-07-22T12:01:00.000Z"};await publishCompletionIntent(intent,j);expect(parseCompletionIntent(await fs.readFile(genesisPaths(ACCOUNT).intent,"utf8"),j)).toEqual(intent);expect(()=>parseCompletionIntent(canonicalString({...intent,accountId:"acct_ffffffffffffffff"}),j)).toThrow();expect(()=>parseCompletionIntent(canonicalString({...intent,path:"relative.txt"}),j)).toThrow();});
  test("RETARGET witness authorizes exactly old or new survivor and retires last",async()=>{const j=await journal(),oldIntent:CompletionIntent={version:1,accountId:ACCOUNT,requestSha256:j.requestSha256,mode:"keychain",keychain:{service:"rbox recovery phrase",account:ACCOUNT,keychainPath:path.resolve(home,"login.keychain")},intentAt:"2026-07-22T12:01:00.000Z"},newIntent:CompletionIntent={version:1,accountId:ACCOUNT,requestSha256:j.requestSha256,mode:"kit-path",path:path.resolve(home,"kit.txt"),intentAt:"2026-07-22T12:02:00.000Z"};await publishCompletionIntent(oldIntent,j);await retargetCompletionIntent(j,oldIntent,newIntent,"2026-07-22T12:03:00.000Z");expect((await reconcileRetargetIntent(j))?.mode).toBe("kit-path");await expect(fs.access(genesisPaths(ACCOUNT).witness)).rejects.toThrow();});
});
