import {afterEach,beforeEach,describe,expect,test} from "bun:test";import fs from "node:fs/promises";import os from "node:os";import path from "node:path";
import {bootstrapAccount,phraseToRk,sha256Hex,utf8} from "../engine/e2ee/index.js";import type {GenesisAccountObservation,GenesisPresence} from "./e2ee-remote.js";import {saveDevice} from "./e2ee-keystore.js";import {genesisPaths,publishGenesisJournal,publishPrepublishMarker,recordGenesisReceipt,stageRecoveryKey,type GenesisJournal} from "./genesis-durable.js";import {classifyEnrollment,hasExactLegacyGenesisPair,type PendingGenesisArtifacts} from "./genesis-enrollment.js";import {genesisQuarantineDir,resumeGenesisQuarantine,startGenesisQuarantine} from "./genesis-quarantine.js";
const ACCOUNT="acct_0123456789abcdef",DEVICE="dev_genesis",ZERO:GenesisPresence={rosters:0,keyStates:0,devices:0,workspaces:0,workspaceKeys:0,e2eePairingTokens:0};let home:string;
beforeEach(async()=>{home=await fs.mkdtemp(path.join(os.tmpdir(),"rbox-genesis-classifier-"));process.env.RBOX_HOME=home;});afterEach(async()=>{delete process.env.RBOX_HOME;await fs.rm(home,{recursive:true,force:true});});
const absent=(present:GenesisPresence=ZERO):GenesisAccountObservation=>({genesisPresenceVersion:1,claim:null,present});
async function complete(){const boot=await bootstrapAccount(ACCOUNT,DEVICE,1_900_000_000_000),present={...ZERO,rosters:1,keyStates:1,devices:1};const claim={genesisPresenceVersion:1 as const,recoveryWrap:JSON.stringify(boot.upload.recoveryWrap),recoveryWrapId:boot.upload.recoveryWrapId,claimCreatedAt:1_900_000_000_000,genesisDeviceId:DEVICE,rosters:[JSON.stringify(boot.upload.genesisRoster)],keyStates:[JSON.stringify(boot.upload.genesisKeyState)],devices:[{deviceId:DEVICE,sigPubkey:boot.upload.device.sigPubKey,encPubkey:boot.upload.device.encPubKey,mkWrap:JSON.stringify(boot.upload.device.mkWrap)}],present,repairTombstone:null};return{boot,observation:{genesisPresenceVersion:1 as const,claim,present,repairTombstone:null} satisfies GenesisAccountObservation};}
const REPAIR="gra_"+"a".repeat(32);
function tomb(present:GenesisPresence=ZERO):GenesisAccountObservation{const claim={genesisPresenceVersion:1 as const,recoveryWrap:"rbox:genesis-repair-tombstone:v1",recoveryWrapId:"rbox:genesis-repair-tombstone:v1",claimCreatedAt:1,genesisDeviceId:null,rosters:[],keyStates:[],devices:[],present,repairTombstone:{version:1 as const,repairId:REPAIR,repairedAt:2}};return{genesisPresenceVersion:1,claim,present,repairTombstone:claim.repairTombstone};}
describe("design 180 enrollment classifier",()=>{
  test("only absent/all-zero/no-local is pristine",async()=>{expect((await classifyEnrollment(ACCOUNT,absent())).kind).toBe("pristine");for(const key of Object.keys(ZERO) as Array<keyof GenesisPresence>){expect((await classifyEnrollment(ACCOUNT,absent({...ZERO,[key]:1}))).kind).toBe("integrity-failure");}});
  test("exact all-zero tombstone is repair-ready and workspace-bearing is fatal",async()=>{const tomb=(workspaces:number):GenesisAccountObservation=>{const present={...ZERO,workspaces};const claim={genesisPresenceVersion:1 as const,recoveryWrap:"rbox:genesis-repair-tombstone:v1",recoveryWrapId:"rbox:genesis-repair-tombstone:v1",claimCreatedAt:1,genesisDeviceId:null,rosters:[],keyStates:[],devices:[],present,repairTombstone:{version:1 as const,repairId:"gra_"+"a".repeat(32),repairedAt:2}};return{genesisPresenceVersion:1,claim,present,repairTombstone:claim.repairTombstone};};expect((await classifyEnrollment(ACCOUNT,tomb(0))).kind).toBe("repair-ready");expect((await classifyEnrollment(ACCOUNT,tomb(1))).kind).toBe("integrity-failure");});
  test("fully verified no-journal account is enrolled",async()=>{expect((await classifyEnrollment(ACCOUNT,(await complete()).observation)).kind).toBe("enrolled");});
  test("exact journal fields classify committed-this-attempt; one request-field mismatch competes",async()=>{const {boot,observation}=await complete();await saveDevice(boot.secrets);await stageRecoveryKey(ACCOUNT,await phraseToRk(boot.recoveryPhrase));const request={recoveryWrap:JSON.stringify(boot.upload.recoveryWrap),recoveryWrapId:boot.upload.recoveryWrapId,genesisRoster:JSON.stringify(boot.upload.genesisRoster),genesisKeyState:JSON.stringify(boot.upload.genesisKeyState),device:{deviceId:DEVICE,sigPubKey:boot.upload.device.sigPubKey,encPubKey:boot.upload.device.encPubKey,mkWrap:JSON.stringify(boot.upload.device.mkWrap)}};const makeJournal=async(requestBody:string):Promise<GenesisJournal>=>({version:1,accountId:ACCOUNT,deviceId:DEVICE,startedAt:"2026-07-22T12:00:00.000Z",phase:"active",requestBody,requestSha256:await sha256Hex(utf8(requestBody)),originalCacheRecovery:false,completionHolds:["recovery-kit-staging"],completionReceipts:{}});const exact=await makeJournal(JSON.stringify(request));await publishGenesisJournal(exact);expect((await classifyEnrollment(ACCOUNT,observation)).kind).toBe("committed-this-attempt");const mismatch=await makeJournal(JSON.stringify({...request,device:{...request.device,sigPubKey:"different"}}));await publishGenesisJournal(mismatch);expect((await classifyEnrollment(ACCOUNT,observation)).kind).toBe("competing-genesis");});
  test("journal and marker tombstone resumes reject all child-bearing inventories",async()=>{for(const key of Object.keys(ZERO) as Array<keyof GenesisPresence>){const present={...ZERO,[key]:1};await publishPrepublishMarker({version:1,accountId:ACCOUNT,deviceId:DEVICE,repairId:REPAIR,startedAt:"2026-07-22T12:00:00.000Z",phase:"prepublish"});expect((await classifyEnrollment(ACCOUNT,tomb(present))).kind).toBe("integrity-failure");await fs.rm(genesisPaths(ACCOUNT).marker);const requestBody=JSON.stringify({recoveryWrap:"rw",recoveryWrapId:"id",genesisRoster:"r",genesisKeyState:"k",device:{deviceId:DEVICE,sigPubKey:"s",encPubKey:"e",mkWrap:"m"},repairId:REPAIR}),journal:GenesisJournal={version:1,accountId:ACCOUNT,deviceId:DEVICE,startedAt:"2026-07-22T12:00:00.000Z",phase:"active",requestBody,requestSha256:await sha256Hex(utf8(requestBody)),originalCacheRecovery:false,completionHolds:["recovery-kit-staging"],completionReceipts:{}};await publishGenesisJournal(journal);expect((await classifyEnrollment(ACCOUNT,tomb(present))).kind).toBe("integrity-failure");await fs.rm(genesisPaths(ACCOUNT).journal);}});
  test("repaired legacy requires the exact realistic old-flow device and MK",async()=>{const {boot}=await complete();await saveDevice(boot.secrets);expect(await hasExactLegacyGenesisPair(ACCOUNT)).toBe(true);expect((await classifyEnrollment(ACCOUNT,tomb())).kind).toBe("repaired-legacy");const raw=JSON.parse(await fs.readFile(genesisPaths(ACCOUNT).device,"utf8"));await fs.writeFile(genesisPaths(ACCOUNT).device,JSON.stringify({...raw,extra:true}));expect((await classifyEnrollment(ACCOUNT,tomb())).kind).toBe("integrity-failure");});
  test("abandoned cleanup classifies cleanup-resume on both quarantine crash boundaries",async()=>{const {boot,observation}=await complete();await saveDevice(boot.secrets);await stageRecoveryKey(ACCOUNT,await phraseToRk(boot.recoveryPhrase));const requestBody=JSON.stringify({recoveryWrap:JSON.stringify(boot.upload.recoveryWrap),recoveryWrapId:boot.upload.recoveryWrapId,genesisRoster:JSON.stringify(boot.upload.genesisRoster),genesisKeyState:JSON.stringify(boot.upload.genesisKeyState),device:{deviceId:DEVICE,sigPubKey:boot.upload.device.sigPubKey,encPubKey:boot.upload.device.encPubKey,mkWrap:JSON.stringify(boot.upload.device.mkWrap)}}),active:GenesisJournal={version:1,accountId:ACCOUNT,deviceId:DEVICE,startedAt:"2026-07-22T12:00:00.000Z",phase:"active",requestBody,requestSha256:await sha256Hex(utf8(requestBody)),originalCacheRecovery:false,completionHolds:["recovery-kit-staging"],completionReceipts:{}};const cleanup=await recordGenesisReceipt(active,{outcome:"competing-cleaned",at:"2026-07-22T12:01:00.000Z"});await startGenesisQuarantine({accountId:ACCOUNT,purpose:"abandoned-attempt",uniquenessKey:cleanup.requestSha256,createdAt:"2026-07-22T12:02:00.000Z"});expect((await classifyEnrollment(ACCOUNT,observation)).kind).toBe("cleanup-resume");await resumeGenesisQuarantine(ACCOUNT,"abandoned-attempt",cleanup.requestSha256,"2026-07-22T12:03:00.000Z");expect((await classifyEnrollment(ACCOUNT,observation)).kind).toBe("cleanup-resume");});
  test("no-claim and tombstone local-presence powersets are closed and conservative",async()=>{
    const fields=["stagedRk","device","mk","intentRaw","witnessRaw"] as const;
    for(let mask=0;mask<(1<<fields.length);mask++){
      const pending:PendingGenesisArtifacts={stagedRk:false,device:false,mk:false,activeQuarantines:[]};
      fields.forEach((field,index)=>{if(mask&(1<<index)){if(field==="intentRaw"||field==="witnessRaw")pending[field]="present";else pending[field]=true;}});
      expect((await classifyEnrollment(ACCOUNT,absent(),pending)).kind).toBe(mask===0?"pristine":"integrity-failure");
      expect((await classifyEnrollment(ACCOUNT,tomb(),pending)).kind).toBe(mask===0?"repair-ready":"integrity-failure");
    }
  });

  test("prepublish marker expected-previous states are exhaustive",async()=>{
    const base:PendingGenesisArtifacts={stagedRk:false,device:false,mk:false,activeQuarantines:[]};
    const ordinary={version:1 as const,accountId:ACCOUNT,deviceId:DEVICE,repairId:null,startedAt:"2026-07-22T12:00:00.000Z",phase:"prepublish" as const};
    const repair={...ordinary,repairId:REPAIR};
    expect((await classifyEnrollment(ACCOUNT,absent(),{...base,marker:ordinary})).kind).toBe("restart-prepublication");
    expect((await classifyEnrollment(ACCOUNT,tomb(),{...base,marker:repair})).kind).toBe("restart-prepublication");
    expect((await classifyEnrollment(ACCOUNT,tomb(),{...base,marker:ordinary})).kind).toBe("integrity-failure");
    expect((await classifyEnrollment(ACCOUNT,absent(),{...base,marker:repair})).kind).toBe("integrity-failure");
    expect((await classifyEnrollment(ACCOUNT,absent(),{...base,marker:ordinary,intentRaw:"orphan"})).kind).toBe("integrity-failure");
    expect((await classifyEnrollment(ACCOUNT,absent({...ZERO,devices:1}),{...base,marker:ordinary})).kind).toBe("integrity-failure");
  });

  test("active journal reaches resume-attempt and receipt reaches cleanup-resume",async()=>{
    const {boot}=await complete();await saveDevice(boot.secrets);await stageRecoveryKey(ACCOUNT,await phraseToRk(boot.recoveryPhrase));
    const requestBody=JSON.stringify({recoveryWrap:JSON.stringify(boot.upload.recoveryWrap),recoveryWrapId:boot.upload.recoveryWrapId,genesisRoster:JSON.stringify(boot.upload.genesisRoster),genesisKeyState:JSON.stringify(boot.upload.genesisKeyState),device:{deviceId:DEVICE,sigPubKey:boot.upload.device.sigPubKey,encPubKey:boot.upload.device.encPubKey,mkWrap:JSON.stringify(boot.upload.device.mkWrap)}});
    const active:GenesisJournal={version:1,accountId:ACCOUNT,deviceId:DEVICE,startedAt:"2026-07-22T12:00:00.000Z",phase:"active",requestBody,requestSha256:await sha256Hex(utf8(requestBody)),originalCacheRecovery:false,completionHolds:["recovery-kit-staging"],completionReceipts:{}};
    await publishGenesisJournal(active);expect((await classifyEnrollment(ACCOUNT,absent())).kind).toBe("resume-attempt");
    await recordGenesisReceipt(active,{outcome:"phrase-delivered",at:"2026-07-22T12:01:00.000Z"});expect((await classifyEnrollment(ACCOUNT,absent())).kind).toBe("cleanup-resume");
  });

  test("precise old-endpoint claim reaches legacy-orphan and near misses fail closed",async()=>{
    const claim={genesisPresenceVersion:1 as const,recoveryWrap:"opaque-wrap",recoveryWrapId:"opaque-id",claimCreatedAt:2,genesisDeviceId:null,rosters:[],keyStates:[],devices:[],present:ZERO,repairTombstone:null};
    const observation={genesisPresenceVersion:1 as const,claim,present:ZERO,repairTombstone:null};
    expect((await classifyEnrollment(ACCOUNT,observation)).kind).toBe("legacy-orphan");
    for(const mutation of [{...claim,recoveryWrap:""},{...claim,recoveryWrapId:""},{...claim,claimCreatedAt:0},{...claim,claimCreatedAt:1.5},{...claim,genesisDeviceId:DEVICE}])expect((await classifyEnrollment(ACCOUNT,{...observation,claim:mutation} as GenesisAccountObservation)).kind).toBe("integrity-failure");
  });

  test("repaired-legacy quarantine stays visible after every rename and becomes inert only when completed",async()=>{
    const {boot}=await complete();await saveDevice(boot.secrets);
    const manifest=await startGenesisQuarantine({accountId:ACCOUNT,purpose:"repaired-legacy",uniquenessKey:REPAIR,createdAt:"2026-07-22T12:00:00.000Z"}),dir=genesisQuarantineDir(ACCOUNT,"repaired-legacy",REPAIR);
    expect((await classifyEnrollment(ACCOUNT,tomb())).kind).toBe("quarantine-resume");
    for(const entry of manifest.entries){await fs.rename(path.join(genesisPaths(ACCOUNT).dir,entry.source),path.join(dir,entry.destination));expect((await classifyEnrollment(ACCOUNT,tomb())).kind).toBe("quarantine-resume");}
    await resumeGenesisQuarantine(ACCOUNT,"repaired-legacy",REPAIR,"2026-07-22T12:01:00.000Z");expect((await classifyEnrollment(ACCOUNT,tomb())).kind).toBe("repair-ready");
  });

  test("abandoned-attempt quarantine stays cleanup-resume after every rename",async()=>{
    const {boot,observation}=await complete();await saveDevice(boot.secrets);await stageRecoveryKey(ACCOUNT,await phraseToRk(boot.recoveryPhrase));
    const requestBody=JSON.stringify({recoveryWrap:JSON.stringify(boot.upload.recoveryWrap),recoveryWrapId:boot.upload.recoveryWrapId,genesisRoster:JSON.stringify(boot.upload.genesisRoster),genesisKeyState:JSON.stringify(boot.upload.genesisKeyState),device:{deviceId:DEVICE,sigPubKey:boot.upload.device.sigPubKey,encPubKey:boot.upload.device.encPubKey,mkWrap:JSON.stringify(boot.upload.device.mkWrap)}}),active:GenesisJournal={version:1,accountId:ACCOUNT,deviceId:DEVICE,startedAt:"2026-07-22T12:00:00.000Z",phase:"active",requestBody,requestSha256:await sha256Hex(utf8(requestBody)),originalCacheRecovery:false,completionHolds:["recovery-kit-staging"],completionReceipts:{}};
    const cleanup=await recordGenesisReceipt(active,{outcome:"competing-cleaned",at:"2026-07-22T12:01:00.000Z"}),manifest=await startGenesisQuarantine({accountId:ACCOUNT,purpose:"abandoned-attempt",uniquenessKey:cleanup.requestSha256,createdAt:"2026-07-22T12:02:00.000Z"}),dir=genesisQuarantineDir(ACCOUNT,"abandoned-attempt",cleanup.requestSha256);
    for(const entry of manifest.entries){await fs.rename(path.join(genesisPaths(ACCOUNT).dir,entry.source),path.join(dir,entry.destination));expect((await classifyEnrollment(ACCOUNT,observation)).kind).toBe("cleanup-resume");}
    await resumeGenesisQuarantine(ACCOUNT,"abandoned-attempt",cleanup.requestSha256,"2026-07-22T12:03:00.000Z");expect((await classifyEnrollment(ACCOUNT,observation)).kind).toBe("cleanup-resume");
  });
});
