import {afterEach,beforeEach,describe,expect,test} from "bun:test";import fs from "node:fs/promises";import os from "node:os";import path from "node:path";
import {genesisPaths,hardenedWrite} from "./genesis-durable.js";import {genesisQuarantineDir,resumeGenesisQuarantine,startGenesisQuarantine} from "./genesis-quarantine.js";
const ACCOUNT="acct_0123456789abcdef",REPAIR="gra_"+"a".repeat(32),ATTEMPT="b".repeat(64);let home:string;
beforeEach(async()=>{home=await fs.mkdtemp(path.join(os.tmpdir(),"rbox-genesis-quarantine-"));process.env.RBOX_HOME=home;});afterEach(async()=>{delete process.env.RBOX_HOME;await fs.rm(home,{recursive:true,force:true});});
async function sources(abandoned=false){const p=genesisPaths(ACCOUNT);if(abandoned)await hardenedWrite(p.stagedRk,"rk");await hardenedWrite(p.device,"device");await hardenedWrite(p.mk,"mk");}
describe("design 180 shared genesis quarantine",()=>{
  for(const row of [{purpose:"repaired-legacy" as const,key:REPAIR,count:2},{purpose:"abandoned-attempt" as const,key:ATTEMPT,count:3}])test(`${row.purpose} is manifest-first and resumable`,async()=>{await sources(row.count===3);const manifest=await startGenesisQuarantine({accountId:ACCOUNT,purpose:row.purpose,uniquenessKey:row.key,createdAt:"2026-07-22T12:00:00.000Z"});expect(manifest.entries).toHaveLength(row.count);const dir=genesisQuarantineDir(ACCOUNT,row.purpose,row.key);expect(await fs.readFile(path.join(dir,"quarantine-resume.json"),"utf8")).toContain(row.purpose);const completed=await resumeGenesisQuarantine(ACCOUNT,row.purpose,row.key,"2026-07-22T12:01:00.000Z");expect(completed.manifestSha256).toMatch(/^[0-9a-f]{64}$/);expect(await fs.readdir(dir)).toContain("completed.json");for(const entry of manifest.entries){await expect(fs.access(path.join(genesisPaths(ACCOUNT).dir,entry.source))).rejects.toThrow();expect(await fs.readFile(path.join(dir,entry.destination),"utf8")).toBe(entry.source==="rk.key.staged"?"rk":entry.source==="device.json"?"device":"mk");}expect(await resumeGenesisQuarantine(ACCOUNT,row.purpose,row.key,"2026-07-22T12:02:00.000Z")).toEqual(completed);});
  test("wrong hashes and illegal both-present state fail closed",async()=>{await sources();const manifest=await startGenesisQuarantine({accountId:ACCOUNT,purpose:"repaired-legacy",uniquenessKey:REPAIR,createdAt:"2026-07-22T12:00:00.000Z"});const dir=genesisQuarantineDir(ACCOUNT,"repaired-legacy",REPAIR);await fs.writeFile(path.join(dir,"device.json"),"duplicate");await expect(resumeGenesisQuarantine(ACCOUNT,"repaired-legacy",REPAIR,"2026-07-22T12:01:00.000Z")).rejects.toThrow(/rename state/);expect(manifest.entries).toHaveLength(2);});
});
