/**
 * zsh shell integration (design 46 — "The zsh plugin").
 *
 * `rbox shell-init zsh` prints this script + the completions to stdout; users add
 * one line to `.zshrc`: `eval "$(rbox shell-init zsh)"`. One binary spawn per shell
 * startup and ZERO spawns afterwards — the per-prompt path is pure zsh builtins
 * (one `read`, parameter math, a glyph map; <2ms budget). All display JUDGMENT
 * lives in TypeScript (renderShellLine in activity.ts): the daemon pre-renders
 * `.rbox/state/shell.line`, this side is deliberately dumb.
 *
 * The plugin is namespaced `_rbox_*` / `_RBOX_*`, registers a chpwd + precmd hook,
 * and degrades to NOTHING on any error (missing/unreadable/malformed/wrong-version
 * sidecar, non-workspace dirs) — visibility must never surface a shell error.
 *
 * The returned script ENDS with {@link zshCompletions} embedded verbatim, so one
 * eval wires both the prompt integration and command completions (no second spawn,
 * no compinit file management).
 */
import { zshCompletions } from "./completions.js";

// The plugin body. Authored as a TS template literal, so every zsh `$`/`${` is
// escaped `\$`/`\${` and zsh backticks are escaped `\`` — the emitted script is
// plain zsh (validated by `zsh -n` in shell-init.test.ts).
const PLUGIN = `# rbox shell integration (design 46) — ambient sync status in your prompt.
# Generated by \`rbox shell-init zsh\`; add \`eval "\$(rbox shell-init zsh)"\` to ~/.zshrc.
# The per-prompt path is pure zsh builtins (no subprocesses): one \`read\` + math.

# Millisecond-free clock (\$EPOCHSECONDS) without ever spawning \`date\`.
zmodload zsh/datetime 2>/dev/null

# Walk up from \$PWD for the workspace marker (git-style); result in \$REPLY, no fork.
_rbox_find_root() {
  local d=\$PWD
  while true; do
    if [[ -r \$d/.rbox/workspace.json ]]; then
      REPLY=\$d
      return 0
    fi
    [[ \$d == / ]] && break
    d=\${d:h}
  done
  REPLY=""
  return 1
}

# Humanize (now - <epoch>) into "just now" / "Nm ago" / "Nh ago" / "Nd ago"; \$REPLY.
_rbox_rel() {
  local secs=\$(( EPOCHSECONDS - \$1 ))
  (( secs < 0 )) && secs=0
  if (( secs < 60 )); then REPLY="just now"
  elif (( secs < 3600 )); then REPLY="\$(( secs / 60 ))m ago"
  elif (( secs < 86400 )); then REPLY="\$(( secs / 3600 ))h ago"
  else REPLY="\$(( secs / 86400 ))d ago"
  fi
}

# Read the pre-rendered sidecar for <root>. Sets _RBOX_KIND (ok|pending|active|halt|
# stale|missing|none) plus _RBOX_NAME/_RBOX_PCT/_RBOX_SEQ/_RBOX_OPEP/_RBOX_OPKIND.
# Any parse problem (unreadable line, wrong version tag, malformed) → none (silent).
_rbox_read() {
  local file=\$1/.rbox/state/shell.line line
  local ver ep st pct seq opep opkind name
  _RBOX_KIND=none
  _RBOX_NAME=""
  _RBOX_PCT=""
  _RBOX_SEQ=""
  _RBOX_OPEP=""
  _RBOX_OPKIND=""
  # Missing file inside a workspace = daemon never wrote it / pre-0.6.4 → "not running".
  if [[ ! -r \$file ]]; then
    _RBOX_KIND=missing
    return
  fi
  IFS= read -r line < \$file || return          # unreadable → none (silent)
  # Peel the 7 fixed fields; \`name\` is the (possibly spacey) remainder.
  ver=\${line%% *};    line=\${line#* }
  ep=\${line%% *};     line=\${line#* }
  st=\${line%% *};     line=\${line#* }
  pct=\${line%% *};    line=\${line#* }
  seq=\${line%% *};    line=\${line#* }
  opep=\${line%% *};   line=\${line#* }
  opkind=\${line%% *}; line=\${line#* }
  name=\$line
  [[ \$ver == v1 ]] || return                    # wrong/absent version tag → none
  [[ \$ep == <-> ]] || return                    # non-numeric heartbeat → none
  # Older than 180s: the daemon heartbeats <=60s while alive, so 3x that is dead.
  if (( EPOCHSECONDS - ep > 180 )); then
    _RBOX_KIND=stale
    _RBOX_NAME=\$name
    return
  fi
  case \$st in
    ok|pending|active|halt) ;;
    *) return ;;                                 # unknown state → none
  esac
  _RBOX_KIND=\$st
  _RBOX_NAME=\$name
  _RBOX_PCT=\$pct
  _RBOX_SEQ=\$seq
  _RBOX_OPEP=\$opep
  _RBOX_OPKIND=\$opkind
}

# Print the one-line entry banner to stderr, colored via prompt escapes (print -P).
_rbox_banner() {
  _rbox_read \$1
  # Double any '%' in the name so it can't inject a prompt escape under \`print -P\`.
  local n=\${_RBOX_NAME//\\%/%%}
  local msg
  case \$_RBOX_KIND in
    ok)
      msg="%F{green}rbox: \$n ✓ in sync"
      [[ \$_RBOX_SEQ != - ]] && msg+=" (seq \$_RBOX_SEQ)"
      if [[ \$_RBOX_OPKIND != - && \$_RBOX_OPEP == <-> ]]; then
        _rbox_rel \$_RBOX_OPEP
        msg+=" · last \$_RBOX_OPKIND \$REPLY"
      fi
      msg+="%f"
      ;;
    pending) msg="%F{yellow}rbox: \$n ↑ syncing…%f" ;;
    active)  msg="%F{cyan}rbox: \$n ↻ \${_RBOX_PCT}%%%f" ;;
    halt)    msg="%F{red}rbox: \$n ⚠ sync halted — run \\\`rbox status\\\`%f" ;;
    stale)   msg="%F{8}rbox: \$n ○ background sync not running — rbox start%f" ;;
    missing) msg="%F{8}rbox: ○ background sync not running — rbox start%f" ;;
    *) return ;;                                 # none → silent, no banner
  esac
  print -P -u2 -- \$msg
}

# Set \$RBOX_PROMPT to the colored glyph ONLY (for RPROMPT or a custom theme slot).
_rbox_glyph() {
  _rbox_read \$1
  case \$_RBOX_KIND in
    ok)            RBOX_PROMPT="%F{green}✓%f" ;;
    pending)       RBOX_PROMPT="%F{yellow}↑%f" ;;
    active)        RBOX_PROMPT="%F{cyan}↻ \${_RBOX_PCT}%%%f" ;;
    halt)          RBOX_PROMPT="%F{red}⚠%f" ;;
    stale|missing) RBOX_PROMPT="%F{8}○%f" ;;
    *)             RBOX_PROMPT="" ;;             # outside/none → empty (segment vanishes)
  esac
}

# chpwd hook: recompute the cached workspace root; banner ONCE on ENTERING a new one.
_rbox_chpwd() {
  _rbox_find_root
  local newroot=\$REPLY
  if [[ \$newroot != \$_RBOX_ROOT ]]; then
    _RBOX_ROOT=\$newroot
    [[ -n \$_RBOX_ROOT ]] && _rbox_banner \$_RBOX_ROOT
  fi
}

# precmd hook: refresh the prompt glyph every prompt (cheap: one \`read\` builtin).
_rbox_precmd() {
  if [[ -n \$_RBOX_ROOT ]]; then
    _rbox_glyph \$_RBOX_ROOT
  else
    RBOX_PROMPT=""
  fi
}

autoload -Uz add-zsh-hook
add-zsh-hook chpwd _rbox_chpwd
add-zsh-hook precmd _rbox_precmd

# Append the glyph to RPROMPT once (idempotent, double-eval safe), unless the user
# opts out to place \$RBOX_PROMPT themselves (p10k / custom themes).
if [[ \${RBOX_NO_RPROMPT:-0} != 1 && \${RPROMPT-} != *'\$RBOX_PROMPT'* ]]; then
  RPROMPT="\${RPROMPT-}"' \$RBOX_PROMPT'
fi

# Prime state so a terminal opened already inside a workspace shows the banner now.
_rbox_chpwd
`;

/** The complete zsh integration script: prompt plugin + embedded completions. */
export function shellInitZsh(): string {
  return `${PLUGIN}\n${zshCompletions()}`;
}
