/**
 * zsh shell integration (design 46 — "The zsh plugin").
 *
 * `rbox shell-init zsh` prints this script + the completions to stdout; users add
 * one line to `.zshrc`: `eval "$(rbox shell-init zsh)"`. One binary spawn per shell
 * startup and ZERO spawns afterwards — the per-prompt path is pure zsh builtins
 * (one `read`, parameter math, a glyph map; <2ms budget). All display JUDGMENT
 * lives in TypeScript (renderShellLine in activity.ts): the daemon pre-renders
 * `.rbox/state/shell.line`, this side is deliberately dumb.
 *
 * The plugin is namespaced `_rbox_*` / `_RBOX_*`, registers a chpwd + precmd hook,
 * and degrades to NOTHING on any error (missing/unreadable/malformed/wrong-version
 * sidecar, non-workspace dirs) — visibility must never surface a shell error.
 *
 * The returned script ENDS with {@link zshCompletions} embedded verbatim, so one
 * eval wires both the prompt integration and command completions (no second spawn,
 * no compinit file management).
 */
import { zshCompletions } from "./completions.js";

const USE_PROMPT_STATUS_BY_DEFAULT = false; // Flip only after the design-88 ≤5ms p99 hyperfine gate passes.

// The plugin body. Authored as a TS template literal, so every zsh `$`/`${` is
// escaped `\$`/`\${` and zsh backticks are escaped `\`` — the emitted script is
// plain zsh (validated by `zsh -n` in shell-init.test.ts).
const PLUGIN = `# rbox shell integration (design 46) — ambient sync status in your prompt.
# Generated by \`rbox shell-init zsh\`; add \`eval "\$(rbox shell-init zsh)"\` to ~/.zshrc.
# The per-prompt path is pure zsh builtins (no subprocesses): one \`read\` + math.

# Millisecond-free clock (\$EPOCHSECONDS) without ever spawning \`date\`.
zmodload zsh/datetime 2>/dev/null

typeset -g _RBOX_PROMPT_STATUS_DEFAULT=${USE_PROMPT_STATUS_BY_DEFAULT ? "1" : "0"}

# Banner colors as LITERAL ANSI escapes for \`print -r\` (raw, expansion-free output).
# NEVER use \`print -P\` on strings containing sidecar data: under PROMPT_SUBST,
# prompt expansion performs command substitution — a workspace NAME containing
# backticks would EXECUTE (codex R1 BLOCKER). Honors NO_COLOR.
if [[ -n \${NO_COLOR-} ]]; then
  typeset -g _RBOX_C_GREEN='' _RBOX_C_YELLOW='' _RBOX_C_CYAN='' _RBOX_C_RED='' _RBOX_C_DIM='' _RBOX_C_OFF=''
else
  typeset -g _RBOX_C_GREEN=\$'\\e[32m' _RBOX_C_YELLOW=\$'\\e[33m' _RBOX_C_CYAN=\$'\\e[36m' \\
             _RBOX_C_RED=\$'\\e[31m' _RBOX_C_DIM=\$'\\e[90m' _RBOX_C_OFF=\$'\\e[0m'
fi

# Walk up from \$PWD for the workspace marker (git-style); result in \$REPLY, no fork.
_rbox_find_root() {
  emulate -L zsh   # user options (SH_WORD_SPLIT, GLOB_SUBST, ...) must not change our expansions
  local d="\$PWD"
  while true; do
    if [[ -r \$d/.rbox/workspace.json ]]; then
      REPLY=\$d
      return 0
    fi
    [[ \$d == / ]] && break
    d=\${d:h}
  done
  REPLY=""
  return 1
}

# Humanize (now - <epoch>) into "just now" / "Nm ago" / "Nh ago" / "Nd ago"; \$REPLY.
_rbox_rel() {
  emulate -L zsh   # user options (SH_WORD_SPLIT, GLOB_SUBST, ...) must not change our expansions
  local secs=\$(( EPOCHSECONDS - \$1 ))
  (( secs < 0 )) && secs=0
  if (( secs < 60 )); then REPLY="just now"
  elif (( secs < 3600 )); then REPLY="\$(( secs / 60 ))m ago"
  elif (( secs < 86400 )); then REPLY="\$(( secs / 3600 ))h ago"
  else REPLY="\$(( secs / 86400 ))d ago"
  fi
}

# Read the pre-rendered sidecar for <root>. Sets _RBOX_KIND (ok|pending|active|halt|
# stale|missing|none) plus _RBOX_NAME/_RBOX_PCT/_RBOX_SEQ/_RBOX_OPEP/_RBOX_OPKIND.
# Any parse problem (unreadable line, wrong version tag, malformed) → none (silent).
_rbox_read() {
  emulate -L zsh   # user options (SH_WORD_SPLIT, GLOB_SUBST, ...) must not change our expansions
  local file="\$1/.rbox/state/shell.line" line
  local ver ep st pct seq opep opkind name
  # =~ writes MATCH/match/MBEGIN/... — localize so a sidecar read never clobbers
  # the user's own regex state (codex R2).
  local MATCH MBEGIN MEND
  local -a match mbegin mend
  _RBOX_KIND=none
  _RBOX_NAME=""
  _RBOX_PCT=""
  _RBOX_SEQ=""
  _RBOX_OPEP=""
  _RBOX_OPKIND=""
  # Missing file inside a workspace = daemon never wrote it / pre-0.6.4 → "not running".
  if [[ ! -r \$file ]]; then
    _RBOX_KIND=missing
    return
  fi
  IFS= read -r line < "\$file" || return        # unreadable → none (silent)
  # WHOLE-LINE shape gate before any field is used (codex R1 MAJOR: naive peeling
  # recycles fields on truncated input — 'v1 <ep> ok' parsed as a valid ok line).
  # The regex pins every field's alphabet, so pct/seq/epochs are digits-or-dash and
  # the state is a known enum BY CONSTRUCTION; anything else → none (silent).
  # Digit counts are CAPPED: an absurd hand-edited epoch would pass an unbounded
  # gate and then make the arithmetic below print "number truncated" at prompt
  # time (codex R2). 12 digits outlives the epoch by ~29k years.
  local pat='^v1 [0-9]{1,12} (ok|pending|active|halt) ([0-9]{1,3}|-) ([0-9]{1,12}|-) ([0-9]{1,12}|-) (push|pull|-) .+\$'
  [[ \$line =~ \$pat ]] || return
  # Peel the 7 fixed fields; \`name\` is the (possibly spacey) remainder.
  ver=\${line%% *};    line=\${line#* }
  ep=\${line%% *};     line=\${line#* }
  st=\${line%% *};     line=\${line#* }
  pct=\${line%% *};    line=\${line#* }
  seq=\${line%% *};    line=\${line#* }
  opep=\${line%% *};   line=\${line#* }
  opkind=\${line%% *}; line=\${line#* }
  # Defense-in-depth: the renderer already strips control chars from the name, but a
  # hand-tampered file must not be able to smuggle terminal escapes to the banner.
  name=\${line//[^[:print:]]/?}
  # Older than 15s: the daemon rewrites shell.line on its 5s ambient heartbeat.
  if (( EPOCHSECONDS - ep > 15 )); then
    _RBOX_KIND=stale
    _RBOX_NAME=\$name
    return
  fi
  _RBOX_KIND=\$st
  _RBOX_NAME=\$name
  _RBOX_PCT=\$pct
  _RBOX_SEQ=\$seq
  _RBOX_OPEP=\$opep
  _RBOX_OPKIND=\$opkind
}

# Decode the writer's encodeURIComponent rel-path using zsh builtins only. \$REPLY.
_rbox_pct_decode() {
  emulate -L zsh
  local s="\$1" out="" hex byte ch
  while [[ -n \$s ]]; do
    ch=\$s[1]
    if [[ \$ch == % ]]; then
      (( \${#s} >= 3 )) || return 1
      hex=\$s[2,3]
      [[ \$hex == [0-9A-Fa-f][0-9A-Fa-f] && \$hex != 00 ]] || return 1
      printf -v byte '%b' "\\\\x\$hex" || return 1
      out+="\$byte"
      s=\$s[4,-1]
    else
      [[ \$ch == [A-Za-z0-9_.\\!\\~\\*\\'\\(\\)-] ]] || return 1
      out+="\$ch"
      s=\$s[2,-1]
    fi
  done
  REPLY=\$out
}

# Read the bounded repo-routing sidecar and select the deepest repo enclosing \$PWD.
# Sets _RBOX_DEF_AGE/_RBOX_DEF_BYTES; malformed, >50-row, or >8KiB files fail closed.
_rbox_deferrals() {
  emulate -L zsh
  setopt extended_glob
  local LC_ALL=C # byte-count semantics for the hard 8KiB gate, including hostile UTF-8
  local root="\$1" file="\$1/.rbox/state/shell.deferrals" header
  local row="" enc reason age changed extra decoded repo best_age="" best_changed="" best_len=-1
  local rows=0 bytes=3 fd cache_key
  local -A file_stat
  _RBOX_DEF_AGE=""
  _RBOX_DEF_BYTES=""
  [[ -r \$file ]] || return 0
  # Exact raw-byte gate before parsing. zstat is an in-process zsh module, not a fork.
  zmodload zsh/stat 2>/dev/null || return 0
  zstat -H file_stat -- "\$file" 2>/dev/null || return 0
  (( file_stat[size] <= 8192 )) || return 0
  cache_key="\$file:\$file_stat[inode]:\$file_stat[size]:\$file_stat[mtime]:\$PWD"
  if [[ \$cache_key == \${_RBOX_DEF_CACHE_KEY-} ]]; then
    _RBOX_DEF_AGE=\${_RBOX_DEF_CACHE_AGE-}
    _RBOX_DEF_BYTES=\${_RBOX_DEF_CACHE_BYTES-}
    return 0
  fi
  exec {fd}<"\$file" || return 0
  IFS= read -r header <&\$fd || { exec {fd}<&-; return 0; }
  [[ \$header == v1 ]] || { exec {fd}<&-; return 0; }
  while IFS= read -r row <&\$fd; do
    (( rows++ ))
    enc="" reason="" age="" changed="" extra=""
    IFS=\$'\\t' read -r enc reason age changed extra <<< "\$row"
    (( bytes += \${#enc} + \${#reason} + \${#age} + \${#changed} + 4 ))
    if (( rows > 50 || bytes > 8192 )) || [[ -z \$enc || "\$row" != "\$enc"\$'\\t'"\$reason"\$'\\t'"\$age"\$'\\t'"\$changed" ]]; then
      exec {fd}<&-
      return 0
    fi
    case \$reason in
      local-edits|local-index|local-operation|local-commits|local-stash|conflict|git-busy|stale-unattributed|worktree-ownership|ignored-target|unreadable|artifact|config|containment|unsupported|other) ;;
      *) exec {fd}<&-; return 0 ;;
    esac
    [[ \$age == ([0-9]m|[1-5][0-9]m|1h|1d|7d|14d|30d) && \$changed == (0|1) ]] || {
      exec {fd}<&-
      return 0
    }
    _rbox_pct_decode "\$enc" || { exec {fd}<&-; return 0; }
    decoded=\$REPLY
    [[ \$decoded == . || ( \$decoded != /* && \$decoded != .. && \$decoded != ../* && \$decoded != */../* && \$decoded != */.. && \$decoded != *//* ) ]] || {
      exec {fd}<&-
      return 0
    }
    # The writer reserves "." as an aggregate overflow fallback. It matches
    # every workspace path here; any explicit repo row wins by being longer.
    [[ \$decoded == . ]] && repo=\$root || repo="\$root/\$decoded"
    if [[ "\$PWD" == "\$repo" || "\$PWD" == "\$repo"/* ]]; then
      if (( \${#repo} > best_len )); then
        best_len=\${#repo}
        best_age=\$age
        best_changed=\$changed
      fi
    fi
  done
  # An unterminated final row makes read fail while leaving its bytes in row.
  # Accepting earlier rows would violate whole-file fail-closed parsing.
  [[ -z \$row ]] || { exec {fd}<&-; return 0; }
  exec {fd}<&-
  _RBOX_DEF_AGE=\$best_age
  _RBOX_DEF_BYTES=\$best_changed
  typeset -g _RBOX_DEF_CACHE_KEY=\$cache_key
  typeset -g _RBOX_DEF_CACHE_AGE=\$best_age
  typeset -g _RBOX_DEF_CACHE_BYTES=\$best_changed
}

_rbox_prompt_status_enabled() {
  emulate -L zsh
  [[ \${RBOX_USE_PROMPT_STATUS:-\$_RBOX_PROMPT_STATUS_DEFAULT} == 1 ]]
}

_rbox_prompt_status() {
  emulate -L zsh
  local bin="\${RBOX_BIN:-rbox}" out
  out="\$("\$bin" prompt-status "\$1" 2>/dev/null)" || return 1
  [[ -n \$out ]] || return 1
  case \$out in
    ✓|○|↑|↑<->|↓|↓<->|\\!*) REPLY=\$out; return 0 ;;
    *) return 1 ;;
  esac
}

_rbox_prompt_status_glyph() {
  emulate -L zsh
  case \$1 in
    ✓) RBOX_PROMPT="%F{green}✓%f" ;;
    ○) RBOX_PROMPT="%F{8}○%f" ;;
    ↑*) RBOX_PROMPT="%F{cyan}\$1%f" ;;
    ↓*) RBOX_PROMPT="%F{cyan}\$1%f" ;;
    \\!*) RBOX_PROMPT="%F{red}\$1%f" ;;
    *) return 1 ;;
  esac
}

# Print the one-line entry banner to stderr. RAW output (\`print -r\`) with literal
# ANSI color variables — never \`print -P\`: prompt expansion would command-substitute
# backticks/\$() in the (tainted) workspace name under PROMPT_SUBST (codex R1 BLOCKER),
# and even our own halt message's backticks would execute.
_rbox_banner() {
  emulate -L zsh   # user options (SH_WORD_SPLIT, GLOB_SUBST, ...) must not change our expansions
  _rbox_read "\$1"
  case \$_RBOX_KIND in
    halt|active|pending) ;;
    *)
      _rbox_deferrals "\$1"
      if [[ -n \$_RBOX_DEF_AGE ]]; then
        local changed=""
        [[ \$_RBOX_DEF_BYTES == 1 ]] && changed=" · working files changed"
        print -r -u2 -- "\${_RBOX_C_YELLOW}rbox: git deferred \${_RBOX_DEF_AGE}\${changed}\${_RBOX_C_OFF}"
        return
      fi
      ;;
  esac
  if _rbox_prompt_status_enabled && _rbox_prompt_status "\$1"; then
    local ps="\$REPLY" msg
    case \$ps in
      ✓) msg="\${_RBOX_C_GREEN}rbox: ✓ in sync\$_RBOX_C_OFF" ;;
      ○) msg="\${_RBOX_C_DIM}rbox: ○ background sync paused\$_RBOX_C_OFF" ;;
      ↑*|↓*) msg="\${_RBOX_C_CYAN}rbox: \$ps syncing\$_RBOX_C_OFF" ;;
      \\!*) msg="\${_RBOX_C_RED}rbox: \$ps — run \\\`rbox status\\\`\$_RBOX_C_OFF" ;;
      *) msg="" ;;
    esac
    [[ -n \$msg ]] && print -r -u2 -- "\$msg"
    return
  fi
  local n="\$_RBOX_NAME"
  local msg
  case \$_RBOX_KIND in
    ok)
      msg="\${_RBOX_C_GREEN}rbox: \$n ✓ in sync"
      [[ \$_RBOX_SEQ != - ]] && msg+=" (seq \$_RBOX_SEQ)"
      if [[ \$_RBOX_OPKIND != - && \$_RBOX_OPEP != - ]]; then
        _rbox_rel "\$_RBOX_OPEP"
        msg+=" · last \$_RBOX_OPKIND \$REPLY"
      fi
      msg+=\$_RBOX_C_OFF
      ;;
    pending) msg="\${_RBOX_C_YELLOW}rbox: \$n ↑ syncing…\$_RBOX_C_OFF" ;;
    active)  msg="\${_RBOX_C_CYAN}rbox: \$n ↻ \${_RBOX_PCT}%\$_RBOX_C_OFF"
             # Indeterminate phase (pct '-', e.g. a live scan): glyph only, no '-%'.
             [[ \$_RBOX_PCT == - ]] && msg="\${_RBOX_C_CYAN}rbox: \$n ↻\$_RBOX_C_OFF" ;;
    halt)    msg="\${_RBOX_C_RED}rbox: \$n ⚠ sync halted — run \\\`rbox status\\\`\$_RBOX_C_OFF" ;;
    stale)   msg="\${_RBOX_C_DIM}rbox: \$n ○ background sync not running — rbox start\$_RBOX_C_OFF" ;;
    missing) msg="\${_RBOX_C_DIM}rbox: ○ background sync not running — rbox start\$_RBOX_C_OFF" ;;
    *) return ;;                                 # none → silent, no banner
  esac
  print -r -u2 -- "\$msg"
}

# Set \$RBOX_PROMPT to the colored glyph ONLY (for RPROMPT or a custom theme slot).
# Prompt escapes (%F) are safe HERE — and only here — because every character of the
# glyph is plugin-authored or regex-pinned to digits (_RBOX_PCT); the tainted name
# never enters it. The active pct is interpolated NOW (not at render), so the stored
# value contains no \$-references of its own.
_rbox_glyph() {
  emulate -L zsh   # user options (SH_WORD_SPLIT, GLOB_SUBST, ...) must not change our expansions
  _rbox_read "\$1"
  case \$_RBOX_KIND in
    halt|active|pending) ;;
    *)
      _rbox_deferrals "\$1"
      if [[ -n \$_RBOX_DEF_AGE ]]; then
        local changed=""
        [[ \$_RBOX_DEF_BYTES == 1 ]] && changed="+files"
        RBOX_PROMPT="%F{yellow}⚠git:\${_RBOX_DEF_AGE}\${changed}%f"
        return
      fi
      ;;
  esac
  if _rbox_prompt_status_enabled && _rbox_prompt_status "\$1"; then
    _rbox_prompt_status_glyph "\$REPLY" && return
  fi
  case \$_RBOX_KIND in
    ok)            RBOX_PROMPT="%F{green}✓%f" ;;
    pending)       RBOX_PROMPT="%F{yellow}↑%f" ;;
    active)        RBOX_PROMPT="%F{cyan}↻ \${_RBOX_PCT}%%%f"
                   [[ \$_RBOX_PCT == - ]] && RBOX_PROMPT="%F{cyan}↻%f" ;;
    halt)          RBOX_PROMPT="%F{red}⚠%f" ;;
    stale|missing) RBOX_PROMPT="%F{8}○%f" ;;
    *)             RBOX_PROMPT="" ;;             # outside/none → empty (segment vanishes)
  esac
}

# chpwd hook: recompute the cached workspace root; banner ONCE on ENTERING a new one.
_rbox_chpwd() {
  emulate -L zsh   # user options (SH_WORD_SPLIT, GLOB_SUBST, ...) must not change our expansions
  _rbox_find_root
  local newroot="\$REPLY"
  if [[ \$newroot != \$_RBOX_ROOT ]]; then
    _RBOX_ROOT=\$newroot
    [[ -n \$_RBOX_ROOT ]] && _rbox_banner "\$_RBOX_ROOT"
  fi
}

# precmd hook: refresh the prompt glyph every prompt (cheap: one \`read\` builtin).
_rbox_precmd() {
  emulate -L zsh   # user options (SH_WORD_SPLIT, GLOB_SUBST, ...) must not change our expansions
  if [[ -n \$_RBOX_ROOT ]]; then
    _rbox_glyph "\$_RBOX_ROOT"
  else
    RBOX_PROMPT=""
  fi
}

autoload -Uz add-zsh-hook
add-zsh-hook chpwd _rbox_chpwd
add-zsh-hook precmd _rbox_precmd

# Append the glyph to RPROMPT once (idempotent, double-eval safe), unless the user
# opts out to place \$RBOX_PROMPT themselves (p10k / custom themes). The embedded
# \$RBOX_PROMPT only expands at render time under PROMPT_SUBST (off in stock zsh —
# without it the right prompt shows the literal string), so auto-append enables it.
# RBOX_NO_RPROMPT=1 is RETROACTIVE (codex R1): a re-eval with it set removes the
# segment — but ONLY when WE auto-appended it in this shell (_RBOX_RPROMPT_APPENDED),
# so a user's own hand-placed ' \$RBOX_PROMPT' is never deleted (codex R2). Prompt
# options are otherwise left untouched — we can't know whether prompt_subst was ours.
if [[ \${RBOX_NO_RPROMPT:-0} == 1 ]]; then
  if [[ \${_RBOX_RPROMPT_APPENDED:-0} == 1 ]]; then
    RPROMPT=\${RPROMPT/' \$RBOX_PROMPT'/}
    _RBOX_RPROMPT_APPENDED=0
  fi
elif [[ \${RPROMPT-} != *'\$RBOX_PROMPT'* ]]; then
  setopt prompt_subst
  RPROMPT="\${RPROMPT-}"' \$RBOX_PROMPT'
  typeset -g _RBOX_RPROMPT_APPENDED=1
fi

# Prime state so a terminal opened already inside a workspace shows the banner now.
_rbox_chpwd
`;

// compinit-order safety (codex R3): eval'd BEFORE compinit — the common stock-.zshrc
// ordering — `compdef` doesn't exist yet, so the completions footer's guarded
// registration silently skipped and compinit does NOT retroactively pick up an
// inline function. Retry at each prompt (one hash lookup) until compinit has run,
// then self-remove. If compinit never runs, completions can't exist anyway and the
// retry stays a ~free no-op.
const COMPDEF_RETRY = `
# Register completions even when this file was eval'd before compinit (see docs).
_rbox_compdef_retry() {
  emulate -L zsh
  (( \$+functions[compdef] )) || return 0
  compdef _rbox rbox 2>/dev/null
  add-zsh-hook -d precmd _rbox_compdef_retry
  unfunction _rbox_compdef_retry
}
if [[ -z \${_comps[rbox]-} ]]; then
  add-zsh-hook precmd _rbox_compdef_retry
fi
`;

/** The complete zsh integration script: prompt plugin + embedded completions. */
export function shellInitZsh(): string {
  return `${PLUGIN}\n${zshCompletions()}\n${COMPDEF_RETRY}`;
}
