export type { FileEntry, FileType, Manifest, GitSection, GitRefScope, GitRefTombstone, GitArtifactRef, GitPackLink } from "./types.js";
export {
  gitPreflight,
  gitRefStorage,
  gitIdentity,
  captureGitState,
  normalizeSymbolicHeadCasing,
  decideDirBundleAllArgs,
  gitCaptureScratchRoot,
  sweepStaleGitCaptureDirs,
  applyGitState,
  GitCaptureDeferredError,
  preserveGitConflict,
  gitSectionBlobRefs,
  gitSectionNewestLink,
  gitSectionPackLinks,
  gitSectionTips,
  validateGitSection,
  isSyncableRef,
  gitIdentityKey,
  projectIdentity,
  assertGitTargetWithinRoot,
  isGitBusy,
  quarantineAndWipeGitState,
  inTreeWorktreeParentRel,
  inTreeWorktreeParentRelFromCtx,
  repoCtxFromDisk,
  inspectGitBusy,
  inspectGitBusyShared,
  setGitSpawnObserver,
  zeroGitChainTimings,
  finalizeGitChainTimings,
  BASE_ABSENT_PREFIX,
  BASE_PRESENT_PREFIX,
  BASE_PRESENT_KEEP_PREFIX,
  SETTLED_ABSENCE_PREFIX,
  MAX_UNSETTLED_BASE_ABSENT,
  MAX_BASE_PRESENT,
  MAX_BASE_PRESENT_KEEP,
  validateRepoIdentityV1,
  encodeRepoIdentityV1,
  repositoryIdentityHash,
  readRepoIdentityV1,
  encodeStateLineageV1,
  readStateLineageV1,
  stateLineageV1FromRealRoot,
  lineageHash,
  artifactBinding,
  bindingForContext,
  repositoryIdentityForContext,
  branchRefHash,
  baseAbsentArtifactRef,
  basePresentArtifactRef,
  basePresentKeepRef,
  settledAbsenceRef,
  baseAbsentPayload,
  basePresentPayload,
  assertBaseArtifactCapacity,
  prepareBaseAbsentArtifact,
  prepareBasePresentArtifact,
  readBaseAbsentArtifact,
  readBaseAbsentArtifactRef,
  inspectBaseAbsentArtifactRef,
  readBasePresentArtifact,
  readBasePresentArtifactRef,
  inspectBasePresentArtifactRef,
  scanBaseArtifacts,
  buildSettledAbsenceTree,
  readSettledAbsence,
  lookupSettledAbsence,
  prepareSettleBaseAbsent,
  prepareRetireSettledAbsence,
  settleBaseAbsentArtifact,
  commitProtocolRefTransaction,
  PROTOCOL_LOCK_ORDER,
  heldProtocolLocks,
  assertProtocolLockHeld,
  setProtocolLockTraceForTests,
  withProtocolLockClass,
  withPostHeadCompatibilityException,
  withCommonDirOperationLocks,
  withRepoOperationLock,
  reflogMaintenanceLockPath,
  withReflogMaintenanceLocks,
  withKeepOriginsLock,
  withRepoProtocolLocks,
  withRepositoryRecoveryFence,
  type ApplyGitResult,
  type ApplyBranchTransitionInput,
  type ApplyBranchTransitionResult,
  type ApplyBranchTransitionAdapter,
  type GitIdentity,
  type GitChainTimings,
  type GitRepoKind,
  type GitPreflightResult,
  type RepoCtx,
  type GitBusyInspection,
  type GitBusyLock,
  type GitBusySharedInspection,
  type RepoIdentityV1,
  type StateLineageV1,
  type ArtifactBinding,
  type BaseAbsentPayload,
  type BasePresentPayload,
  type SettledAbsenceMeta,
  type PreparedProtocolRef,
  type PreparedBasePresent,
  type ArtifactInvalidReason,
  type ArtifactReadResult,
  type SettledAbsenceLedger,
  type SettledAbsenceReadResult,
  type PreparedSettledAbsence,
  type PreparedSettledAbsenceRetirement,
  type BaseArtifactScan,
  type ForeignBaseArtifactScanEntry,
  type ProtocolLockClass,
  type ProtocolLockTraceEvent,
  type RepositoryProtocolFenceRequest,
} from "./git-state.js";
export { discoverGitRepos, discoverGitReposUnder, type DiscoveredGitRepo } from "./git-discover.js";
export {
  generateKek,
  kekToPhrase,
  kekFromPhrase,
  encryptFileToTemp,
  decryptFileToPath,
  isSourceChangedError,
  zstdCompress,
  zstdDecompressCapped,
  type EncryptedBlob,
  type EncryptFileOptions,
} from "./crypto.js";
export { readManifestChain } from "./manifest-chain.js";
export {
  MANIFEST_ENVELOPE_MAGIC,
  MANIFEST_ENVELOPE_PREFIX,
  MAX_ENVELOPE_HEADER,
  MAX_MANIFEST_PLAINTEXT,
  MAX_MANIFEST_DELTA_CHAIN,
  ManifestChainError,
  canonicalManifestBytes,
  canonicalManifestHash,
  canonicalManifestHashStreaming,
  encodeSnapshotEnvelope,
  diffToOps,
  encodeDeltaEnvelope,
  decodeEnvelope,
  hasEnvelopePrefix,
  foldDelta,
  type ManifestDeltaHeader,
  type ManifestDeltaOp,
  type DecodedManifestEnvelope,
} from "./manifest-delta.js";
export { cryptoPoolStatus, shutdownCryptoPool, withCryptoPool, type CryptoPoolStatus, type CryptoPool, type CoalescedBlob } from "./crypto-pool.js";
export { hashFile, hashBytes } from "./hash.js";
export {
  ALWAYS_NATIVE_PRUNE,
  BUILTIN_IGNORE,
  GIT_REF_SIGNAL_TAIL_TABLE,
  HARD_PRUNE_DIRS,
  isGitRefSignal,
  isGitRefSignalTail,
  nativePruneGlobs,
  buildIgnoreMatcher,
  effectiveIgnoreRules,
  isIgnoreRuleFile,
  type BuildIgnoreMatcherOptions,
  type IgnoreMatcher,
  type IgnoreRule,
} from "./ignore.js";
export { scanManifest, createScanStats, applyWatchEvents, compareManifestPaths, statsStableAcrossHash, isPresentButUnreadableError, type ScanStats, type DirProbeSample, type DirProbeSink, type WatchEvent, type WatchEventKind } from "./manifest.js";
export { diffManifests, indexByPath, sameContent, type ManifestDiff } from "./diff.js";
export { LocalBlobStore, type BlobStore } from "./blobstore.js";
export { reconcile, conflictName, type Action } from "./reconcile.js";
export {
  conservativeReceiverEquivalentPath,
  oracleFromPull,
  oracleFromState,
  probeReceiverEquivalence,
  receiverEquivalentCollisionNames,
  receiverEquivalentPath,
  setReceiverEquivalenceProbeForTests,
  type AppliedManifestOracle,
  type OracleVerdict,
  type ReceiverEquivalence,
  type ReceiverEquivalenceProbe,
} from "./apply-receipt.js";
export { applyActions, actionPath,
  laneTimingSummary, restoreEntryToPath, uploadManifestBlobs } from "./apply.js";
export {
  applyStatsDelta, applyStatsEnabled, setApplyStatsEnabled, snapshotApplyStats,
  type ApplyStats,
} from "./apply-stats.js";
export { poolMap } from "./pool.js";
export { PhaseReport, type PhaseName, type PhaseTotals, type PhaseBytes, type PhaseReportJson } from "./phase-report.js";
export { HashCache, type HashCacheEntry } from "./hashcache.js";
export {
  DirCache,
  RACY_MARGIN_MS,
  UNPRUNED_DEADLINE_MS,
  coverageOf,
  dirListingReusable,
  scanPruneEnabled,
  type ChildType,
  type DirCacheChild,
  type DirCacheEntry,
  type DirCacheFile,
  type DircacheOutcome,
  type RuleFileRecord,
} from "./dircache.js";
export {
  EncryptAddressCache,
  EncryptAddressCacheWriter,
  ENCRYPT_ADDRESS_CACHE_REL,
  type EncryptAddressCacheContext,
  type EncryptAddressCacheEntry,
} from "./encrypt-address-cache.js";
export { writeFileAtomic, RBOX_TMP_PREFIX } from "./fsutil.js";
export { indexIdentityV2 } from "./git/index-identity.js";
export {
  buildPRepairQ,
  parsePRepairQ,
  pRepairQRef,
  pRepairReason,
  pRepairBaseDisposition,
  byteProjection,
  skeepHash,
  pRepairRetryAction,
  pRepairEviction,
  buildPRepairReceipt,
  parsePRepairReceipt,
  MAX_P_REPAIR_Q_BYTES,
  MAX_P_REPAIR_Q_PER_LINEAGE,
  P_REPAIR_Q_PREFIX,
  type ByteProjection,
  type PRepairQ,
  type BuildPRepairQInput,
  type PRepairReceipt,
  type PRepairRetryObservation,
  type PRepairRetryAction,
  type PRepairQEntry,
} from "./git/p-repair.js";
export {
  reflogObservation,
  observePRepair,
  enumeratePRepairQ,
  inspectPRepairReceipt,
  inspectLockedPRepairReceipt,
  cleanupPRepairLineage,
  cleanupLockedPRepairLineage,
  runPRepairAttempt,
  runLockedPRepairAttempt,
  resumeAcceptedPRepair,
  resumeLockedAcceptedPRepair,
  refreshAcceptedPRepair,
  refreshLockedAcceptedPRepair,
  persistPRepairTerminal,
  type PRepairStateSnapshot,
  type PRepairStatePort,
  type PRepairLockedObservation,
  type PRepairAttemptInput,
  type PRepairAttemptResult,
  type PRepairResumeResult,
  type PRepairObservation,
  type PRepairCrashPoint,
} from "./git/p-repair-transaction.js";
export {
  incomingOwnershipRoots,
  partitionOwnedByIncoming,
  tipOwnedByIncoming,
  noDropProof,
  enumerateStashReflogOids,
  type ImportedScratchNamespace,
  type OwnershipProof,
  type PartitionedOwnership,
  type NoDropProof,
} from "./git/reachability.js";
export {
  prepareKeepPins,
  prepareTombstonePrunePins,
  withPreparedTombstonePrunePins,
  verifyPreparedTombstoneFingerprint,
  readRefReflogFingerprint,
  parseKeepPinOrigins,
  expireTombstonePinOrigins,
  expireTombstoneKeepPins,
  TOMBSTONE_PIN_RETENTION_MS,
  runPreparedUpdateRefTransaction,
  PreparedRefTransactionPrepareError,
  keepPinRef,
  readKeepPinOrigins,
  repairOriginOids,
  pinRepairObjectsFirst,
  mergeRepairOrigins,
  verifyRepairKeepRefs,
  prepareRepairOriginCleanup,
  withPreparedRepairOriginCleanup,
  prepareCreateOnlyKeepPins,
  rewriteKeepPinOrigins,
  filterKeepPinOrigins,
  pinDisplaced,
  enumerateRefReflogOids,
  prepareDisplacedRefPins,
  type KeepPinOrigin,
  type KeepPinOrigins,
  type PreparedKeepPins,
  type PreparedTombstonePins,
  type PrepareDisplacedPinsResult,
} from "./git/keep-pins.js";
export {
  checkoutJournalDir,
  checkoutJournalPresent,
  writeCheckoutJournal,
  updateCheckoutJournal,
  markCheckoutJournalPublished,
  clearCheckoutJournal,
  recoverJournal,
  type CheckoutJournalBinding,
  type CheckoutJournal,
  type WriteCheckoutJournalSources,
  type JournalRecoveryResult,
} from "./git/journal.js";
export {
  commitCheckout,
  checkoutTransactionCapability,
  checkoutTransactionSupported,
  ownershipAwareGitBusy,
  setCheckoutCapabilityProbeForTests,
  resetCheckoutCapabilityProbeCacheForTests,
  ORIG_HEAD_CHANGED_AT_CHECKOUT_BOUNDARY,
  type CheckoutRefUpdate,
  type CheckoutHeadUpdate,
  type CheckoutPlan,
  type OwnedGitLock,
  type SecondProofContext,
  type CommitCheckoutOptions,
  type CommitCheckoutResult,
  type CheckoutCapabilityProbe,
  type CheckoutTransactionCapability,
  type CheckoutTransactionCapabilityStatus,
} from "./git/checkout-txn.js";
export {
  validateManifest,
  validateGitRepos,
  validateRefTombstones,
  manifestRequiresSchema4,
  isSafeRelPath,
  caseFoldCollisionGroups,
  manifestPathCaseFold,
  type ValidationResult,
  type CaseFoldCollisionGroup,
  MAX_PATH_BYTES,
  MAX_ENTRIES,
  MAX_MANIFEST_BYTES,
  MAX_SYMLINK_TARGET_BYTES,
  KNOWN_MANIFEST_SCHEMA,
  MAX_PACK_CHAIN,
  MAX_GIT_REPOS,
  MAX_REF_TOMBSTONES_PER_REF,
  MAX_REF_TOMBSTONES_PER_REPO,
} from "./manifest-validate.js";
export {
  detectProjects,
  hydrateArgv,
  ECOSYSTEM_RULES,
  type DetectedProject,
  type DetectHints,
  type EcosystemRule,
  type Ecosystem,
} from "./detect.js";
export {
  evaluateReadiness,
  parseMajor,
  minMajor,
  satisfiesMajor,
  type HostTool,
  type ProjectProbe,
  type ProjectReadiness,
  type ReadinessReport,
  type VersionRequirement,
} from "./doctor.js";
export {
  abortGeneration,
  candidateRef,
  discardGeneration,
  inspectOwner,
  publishGeneration,
  registerWorker,
  replaceInternedEntry,
  withCipherDescriptor,
  withGenerationOwnerScope,
  workerRequest,
  EntryArena,
  EntryShapeError,
  GenerationOwnerCapabilityError,
  GenerationReplacementConflict,
  PublishedGeneration,
  WorkerLifecycleError,
  type CipherDescriptor,
  type EntryLease,
  type EntryVersionToken,
  type GenerationMutationToken,
  type GenerationOwnerLease,
  type GenerationOwnerScope,
  type OwnedEntryRef,
  type PublishedGenerationToken,
  type WorkerEntryRequest,
  type WorkerRegistration,
} from "./entry-arena/index.js";
