import {env,SELF,applyD1Migrations} from "cloudflare:test";
import {beforeAll,describe,expect,test} from "vitest";

const BASE="https://example.com";const PLATFORM={"x-rbox-platform":"test-platform-secret","content-type":"application/json"};
beforeAll(async()=>{await applyD1Migrations(env.rbox_dev_db,env.TEST_MIGRATIONS);});
async function account(name:string){const r=await SELF.fetch(`${BASE}/v1/auth/device/bootstrap`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({secret:"test-bootstrap-secret",accountName:name})});expect(r.status).toBe(200);return r.json() as Promise<{token:string;accountId:string;deviceId:string}>;}
const auth=(token:string,extra:Record<string,string>={})=>({authorization:`Bearer ${token}`,...extra});
const body=(deviceId:string,repairId?:string)=>({recoveryWrap:"rw",recoveryWrapId:"rwid",genesisRoster:"roster-v0",genesisKeyState:"keystate-0",device:{deviceId,sigPubKey:"sig",encPubKey:"enc",mkWrap:"mk"},...(repairId?{repairId}:{})});
async function bootstrapKeys(a:{token:string;deviceId:string},over:Record<string,unknown>={},cap=true){return SELF.fetch(`${BASE}/v1/keys/bootstrap`,{method:"POST",headers:auth(a.token,{"content-type":"application/json",...(cap?{"x-rbox-genesis-capability":"1"}:{})}),body:JSON.stringify({...body(a.deviceId),...over})});}
const repairBody=(accountId:string,dryRun:boolean)=>JSON.stringify({accountId,operator:"on-call@example.com",reason:"support case RBOX-180: split genesis",dryRun});

describe("design 180 atomic genesis",()=>{
  test("absent observation is exhaustive version 1",async()=>{const a=await account("g180-absent");const r=await SELF.fetch(`${BASE}/v1/keys/account`,{headers:auth(a.token)});expect(r.status).toBe(404);expect(await r.json()).toEqual({error:"not_found",genesisPresenceVersion:1,present:{rosters:0,keyStates:0,devices:0,workspaces:0,workspaceKeys:0,e2eePairingTokens:0}});});

  test("ordinary publication is all-four atomic and exact-field idempotent",async()=>{const a=await account("g180-ordinary");expect((await bootstrapKeys(a)).status).toBe(200);expect((await bootstrapKeys(a)).status).toBe(200);expect((await bootstrapKeys(a,{genesisRoster:"different"})).status).toBe(409);const counts=await env.rbox_dev_db.prepare(`SELECT (SELECT COUNT(*) FROM account_keys WHERE account_id=?1) a,(SELECT COUNT(*) FROM rosters WHERE account_id=?1) r,(SELECT COUNT(*) FROM account_key_states WHERE account_id=?1) k,(SELECT COUNT(*) FROM device_keys WHERE account_id=?1) d`).bind(a.accountId).first<{a:number;r:number;k:number;d:number}>();expect(counts).toEqual({a:1,r:1,k:1,d:1});});

  test("admin dry-run audits and execute installs a non-pristine tombstone",async()=>{const a=await account("g180-repair");await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at) VALUES(?,?,?,?)").bind(a.accountId,"legacy-wrap","legacy-id",123).run();const hidden=await SELF.fetch(`${BASE}/v1/admin/account/${a.accountId}/genesis-repair`,{method:"POST",headers:{"content-type":"application/json"},body:repairBody(a.accountId,true)});expect(hidden.status).toBe(404);
    const dry=await SELF.fetch(`${BASE}/v1/admin/account/${a.accountId}/genesis-repair`,{method:"POST",headers:PLATFORM,body:repairBody(a.accountId,true)});expect(dry.status).toBe(200);expect(await dry.json()).toMatchObject({ok:true,dryRun:true,classification:"exact_legacy_orphan",result:"no_change"});
    const exec=await SELF.fetch(`${BASE}/v1/admin/account/${a.accountId}/genesis-repair`,{method:"POST",headers:PLATFORM,body:repairBody(a.accountId,false)});expect(exec.status).toBe(200);const result=await exec.json() as {repairId:string;auditId:string};expect(result.repairId).toBe(result.auditId);
    const observed=await SELF.fetch(`${BASE}/v1/keys/account`,{headers:auth(a.token)});expect(observed.status).toBe(200);expect(await observed.json()).toMatchObject({genesisPresenceVersion:1,recoveryWrap:"rbox:genesis-repair-tombstone:v1",repairTombstone:{version:1,repairId:result.repairId},present:{rosters:0,keyStates:0,devices:0,workspaces:0,workspaceKeys:0,e2eePairingTokens:0}});
    expect((await bootstrapKeys(a,{repairId:result.repairId},false)).status).toBe(428);expect((await bootstrapKeys(a,{},false)).status).toBe(423);const repaired=await bootstrapKeys(a,{repairId:result.repairId},true);expect({status:repaired.status,body:await repaired.json()}).toEqual({status:200,body:{ok:true}});const replay=await bootstrapKeys(a,{repairId:result.repairId},true);expect({status:replay.status,body:await replay.json()}).toEqual({status:200,body:{ok:true,idempotent:true}});
  });

  test("tombstone and erasure fences precede workspace side effects",async()=>{const a=await account("g180-fence");await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(a.accountId,"rbox:genesis-repair-tombstone:v1","rbox:genesis-repair-tombstone:v1",1,"gra_"+"a".repeat(32),2).run();const ws=await SELF.fetch(`${BASE}/v1/workspaces?project=root`,{method:"POST",headers:auth(a.token)});expect(ws.status).toBe(423);expect(await ws.json()).toEqual({error:"repair_in_progress"});expect(await env.rbox_dev_db.prepare("SELECT 1 FROM workspaces WHERE account_id=?").bind(a.accountId).first()).toBeNull();
    await env.rbox_dev_db.prepare("INSERT INTO account_deletions(account_id,requested_at,purge_after,status) VALUES(?,?,?,'done')").bind(a.accountId,1,1).run();const erased=await SELF.fetch(`${BASE}/v1/workspaces?project=root`,{method:"POST",headers:auth(a.token)});expect(erased.status).toBe(410);expect(await erased.json()).toEqual({error:"account_erased"});});
});
