import {env,SELF,applyD1Migrations} from "cloudflare:test";
import {beforeAll,describe,expect,test} from "vitest";
import {GENESIS_TOMBSTONE_SENTINEL,genesisRepair} from "../src/genesis-repair.js";
import {bootstrapAccountKeys,getAccountKeys,type KeyBootstrapBody} from "../src/keys.js";
import {finishD1} from "../src/account-delete.js";
import {createWorkspace} from "../src/authz.js";
import {syncRoutes} from "../src/routes/sync.js";

const BASE="https://example.com";const PLATFORM={"x-rbox-platform":"test-platform-secret","content-type":"application/json"};
beforeAll(async()=>{await applyD1Migrations(env.rbox_dev_db,env.TEST_MIGRATIONS);});
async function account(name:string){const r=await SELF.fetch(`${BASE}/v1/auth/device/bootstrap`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({secret:"test-bootstrap-secret",accountName:name})});expect(r.status).toBe(200);return r.json() as Promise<{token:string;accountId:string;deviceId:string}>;}
const auth=(token:string,extra:Record<string,string>={})=>({authorization:`Bearer ${token}`,...extra});
const body=(deviceId:string,repairId?:string)=>({recoveryWrap:"rw",recoveryWrapId:"rwid",genesisRoster:"roster-v0",genesisKeyState:"keystate-0",device:{deviceId,sigPubKey:"sig",encPubKey:"enc",mkWrap:"mk"},...(repairId?{repairId}:{})});
async function bootstrapKeys(a:{token:string;deviceId:string},over:Partial<KeyBootstrapBody>={},cap=true){return SELF.fetch(`${BASE}/v1/keys/bootstrap`,{method:"POST",headers:auth(a.token,{"content-type":"application/json",...(cap?{"x-rbox-genesis-capability":"1"}:{})}),body:JSON.stringify({...body(a.deviceId),...over})});}
const repairBody=(accountId:string,dryRun:boolean)=>JSON.stringify({accountId,operator:"on-call@example.com",reason:"support case RBOX-180: split genesis",dryRun});
const adminRepair=(accountId:string,dryRun=false)=>SELF.fetch(`${BASE}/v1/admin/account/${accountId}/genesis-repair`,{method:"POST",headers:PLATFORM,body:repairBody(accountId,dryRun)});
/** The two database members this suite doubles; widened so `D1Database` satisfies it. */
interface CaptureDb{prepare(sql:string):D1PreparedStatement;batch(statements:D1PreparedStatement[]):Promise<D1Result[]>;}

async function oldClaim(accountId:string,wrap="legacy-wrap",wrapId="legacy-id",createdAt=123){await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at) VALUES(?,?,?,?)").bind(accountId,wrap,wrapId,createdAt).run();}

describe("design 180 atomic genesis",()=>{
  test("account observation refuses split directory/data bindings before SQL",async()=>{let reads=0;const first={},second={},split=Object.defineProperty({},"rbox_dev_db",{get(){return reads++===0?first:second;}});await expect(getAccountKeys(split as never,{accountId:"acct_0123456789abcdef",deviceId:"dev_x"} as never)).rejects.toThrow(/N=1 sharding blocker/);expect(reads).toBe(2);});
  test("absent observation is exhaustive version 1",async()=>{const a=await account("g180-absent");const r=await SELF.fetch(`${BASE}/v1/keys/account`,{headers:auth(a.token)});expect(r.status).toBe(404);expect(await r.json()).toEqual({error:"not_found",genesisPresenceVersion:1,present:{rosters:0,keyStates:0,devices:0,workspaces:0,workspaceKeys:0,e2eePairingTokens:0}});});

  test("ordinary publication is all-four atomic and exact-field idempotent",async()=>{const a=await account("g180-ordinary");expect((await bootstrapKeys(a)).status).toBe(200);expect((await bootstrapKeys(a)).status).toBe(200);expect((await bootstrapKeys(a,{genesisRoster:"different"})).status).toBe(409);const counts=await env.rbox_dev_db.prepare(`SELECT (SELECT COUNT(*) FROM account_keys WHERE account_id=?1) a,(SELECT COUNT(*) FROM rosters WHERE account_id=?1) r,(SELECT COUNT(*) FROM account_key_states WHERE account_id=?1) k,(SELECT COUNT(*) FROM device_keys WHERE account_id=?1) d`).bind(a.accountId).first<{a:number;r:number;k:number;d:number}>();expect(counts).toEqual({a:1,r:1,k:1,d:1});});

  test("every logical statement failure rolls back ordinary and tombstone-replacement batches",async()=>{
    const statements=[{table:"account_keys",event:"INSERT"},{table:"rosters",event:"INSERT"},{table:"account_key_states",event:"INSERT"},{table:"device_keys",event:"INSERT"}] as const;
    for(const mode of ["ordinary","repair"] as const)for(const [index,statement] of statements.entries()){const a=await account(`g180-batch-fail-${mode}-${index}`),repairId=`gra_b${index.toString(16)}${"0".repeat(30)}`;if(mode==="repair")await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(a.accountId,GENESIS_TOMBSTONE_SENTINEL,GENESIS_TOMBSTONE_SENTINEL,1,repairId,2).run();const trigger=`g180_fail_${mode}_${index}`,event=mode==="repair"&&statement.table==="account_keys"?"UPDATE":statement.event,row=event==="UPDATE"?"OLD":"NEW";await env.rbox_dev_db.prepare(`CREATE TRIGGER ${trigger} BEFORE ${event} ON ${statement.table} WHEN ${row}.account_id='${a.accountId}' BEGIN SELECT RAISE(ABORT,'g180 injected statement failure'); END`).run();try{await expect(bootstrapAccountKeys(env,{accountId:a.accountId,deviceId:a.deviceId} as never,body(a.deviceId,mode==="repair"?repairId:undefined),"1")).rejects.toThrow(/injected statement failure/);}finally{await env.rbox_dev_db.prepare(`DROP TRIGGER ${trigger}`).run();}const counts=await env.rbox_dev_db.prepare(`SELECT (SELECT COUNT(*) FROM account_keys WHERE account_id=?1) a,(SELECT COUNT(*) FROM rosters WHERE account_id=?1) r,(SELECT COUNT(*) FROM account_key_states WHERE account_id=?1) k,(SELECT COUNT(*) FROM device_keys WHERE account_id=?1) d`).bind(a.accountId).first();expect(counts,`${mode}:${statement.table}`).toEqual({a:mode==="repair"?1:0,r:0,k:0,d:0});if(mode==="repair")expect(await env.rbox_dev_db.prepare("SELECT recovery_wrap,repair_id FROM account_keys WHERE account_id=?").bind(a.accountId).first()).toEqual({recovery_wrap:GENESIS_TOMBSTONE_SENTINEL,repair_id:repairId});}
  });

  test("every repair-bootstrap statement repeats the state predicate and refuses the whole batch",async()=>{
    const captured:string[]=[];const captureAccount=await account("g180-repair-predicate-capture"),captureRepairId=`gra_d0${"0".repeat(30)}`;await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(captureAccount.accountId,GENESIS_TOMBSTONE_SENTINEL,GENESIS_TOMBSTONE_SENTINEL,1,captureRepairId,2).run();
    const realDb=env.rbox_dev_db,captureDb:CaptureDb={prepare(sql:string){if(/^\s*(?:INSERT INTO (?:rosters|account_key_states|device_keys)|UPDATE account_keys SET)/.test(sql))captured.push(sql);return realDb.prepare(sql);},batch:async()=>Array.from({length:4},()=>({meta:{changes:0}} as D1Result))};
    const capturedRefusal=await bootstrapAccountKeys({...env,rbox_dev_db:captureDb as D1Database},{accountId:captureAccount.accountId,deviceId:captureAccount.deviceId} as never,body(captureAccount.deviceId,captureRepairId),"1");expect(capturedRefusal.status).toBe(423);expect(captured).toHaveLength(4);
    const now=1_800_000_000_000,roster="target-roster",keyState="target-state",sig="target-sig",enc="target-enc",mk="target-mk";
    const seedPrefix=async(index:number,accountId:string,deviceId:string)=>{if(index>=1)await realDb.prepare("INSERT INTO rosters(account_id,version,signed,created_at) VALUES(?,0,?,?)").bind(accountId,roster,now).run();if(index>=2)await realDb.prepare("INSERT INTO account_key_states(account_id,account_epoch,signed,created_at) VALUES(?,0,?,?)").bind(accountId,keyState,now).run();if(index>=3)await realDb.prepare("INSERT INTO device_keys(device_id,account_id,sig_pubkey,enc_pubkey,mk_wrap,created_at) VALUES(?,?,?,?,?,?)").bind(deviceId,accountId,sig,enc,mk,now).run();};
    const falsify=[
      (id:string)=>realDb.prepare("INSERT INTO rosters(account_id,version,signed,created_at) VALUES(?,7,'foreign-roster',7)").bind(id).run(),
      (id:string)=>realDb.prepare("INSERT INTO account_key_states(account_id,account_epoch,signed,created_at) VALUES(?,7,'foreign-state',7)").bind(id).run(),
      (id:string)=>realDb.prepare("INSERT INTO device_keys(device_id,account_id,sig_pubkey,enc_pubkey,mk_wrap,created_at) VALUES(?,?,'foreign-sig','foreign-enc','foreign-mk',7)").bind(`dev_foreign_${id}`,id).run(),
      (id:string)=>realDb.prepare("INSERT INTO workspaces(workspace_id,project_id,account_id,created_at) VALUES(?,'root',?,7)").bind(`ws_foreign_${id}`,id).run(),
    ];
    for(const [index,label] of ["roster insert","key-state insert","device insert","claim update"].entries()){
      const a=await account(`g180-repair-predicate-${index}`),repairId=`gra_d${(index+1).toString(16)}${"0".repeat(30)}`;await realDb.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(a.accountId,GENESIS_TOMBSTONE_SENTINEL,GENESIS_TOMBSTONE_SENTINEL,1,repairId,2).run();await seedPrefix(index,a.accountId,a.deviceId);await falsify[index]!(a.accountId);
      const snapshot=await getAccountKeys(env,{accountId:a.accountId,deviceId:a.deviceId} as never);const before=await snapshot.text();
      const isolated=await realDb.prepare(captured[index]!).bind(a.accountId,"rw","rwid",now,a.deviceId,roster,keyState,sig,enc,mk,GENESIS_TOMBSTONE_SENTINEL,repairId,1).run();expect(isolated.meta.changes,label).toBe(0);
      const response=await bootstrapAccountKeys(env,{accountId:a.accountId,deviceId:a.deviceId} as never,{recoveryWrap:"rw",recoveryWrapId:"rwid",genesisRoster:roster,genesisKeyState:keyState,device:{deviceId:a.deviceId,sigPubKey:sig,encPubKey:enc,mkWrap:mk},repairId},"1");expect(response.status,label).toBe(423);expect(await response.json(),label).toEqual({error:"repair_in_progress"});
      const after=await getAccountKeys(env,{accountId:a.accountId,deviceId:a.deviceId} as never);expect(await after.text(),label).toBe(before);
    }
  });

  test("exact idempotency rejects mutations of all eight fields after replay wins ordering",async()=>{const a=await account("g180-eight-fields");expect((await bootstrapKeys(a)).status).toBe(200);expect((await bootstrapKeys(a)).status).toBe(200);const base=body(a.deviceId),variants=[{...base,recoveryWrap:"x"},{...base,recoveryWrapId:"x"},{...base,genesisRoster:"x"},{...base,genesisKeyState:"x"},{...base,device:{...base.device,deviceId:"dev_other"}},{...base,device:{...base.device,sigPubKey:"x"}},{...base,device:{...base.device,encPubKey:"x"}},{...base,device:{...base.device,mkWrap:"x"}}];for(const variant of variants){const r=await SELF.fetch(`${BASE}/v1/keys/bootstrap`,{method:"POST",headers:auth(a.token,{"content-type":"application/json","x-rbox-genesis-capability":"1"}),body:JSON.stringify(variant)});expect(r.status).toBe(409);expect(await r.json()).toEqual({error:"already_bootstrapped"});}});

  test("admin dry-run audits and execute installs a non-pristine tombstone",async()=>{const a=await account("g180-repair");await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at) VALUES(?,?,?,?)").bind(a.accountId,"legacy-wrap","legacy-id",123).run();const hidden=await SELF.fetch(`${BASE}/v1/admin/account/${a.accountId}/genesis-repair`,{method:"POST",headers:{"content-type":"application/json"},body:repairBody(a.accountId,true)});expect(hidden.status).toBe(404);
    const dry=await SELF.fetch(`${BASE}/v1/admin/account/${a.accountId}/genesis-repair`,{method:"POST",headers:PLATFORM,body:repairBody(a.accountId,true)});expect(dry.status).toBe(200);expect(await dry.json()).toMatchObject({ok:true,dryRun:true,classification:"exact_legacy_orphan",result:"no_change"});
    const exec=await SELF.fetch(`${BASE}/v1/admin/account/${a.accountId}/genesis-repair`,{method:"POST",headers:PLATFORM,body:repairBody(a.accountId,false)});expect(exec.status).toBe(200);const result=await exec.json() as {repairId:string;auditId:string};expect(result.repairId).toBe(result.auditId);
    const observed=await SELF.fetch(`${BASE}/v1/keys/account`,{headers:auth(a.token)});expect(observed.status).toBe(200);expect(await observed.json()).toMatchObject({genesisPresenceVersion:1,recoveryWrap:"rbox:genesis-repair-tombstone:v1",repairTombstone:{version:1,repairId:result.repairId},present:{rosters:0,keyStates:0,devices:0,workspaces:0,workspaceKeys:0,e2eePairingTokens:0}});
    expect((await bootstrapKeys(a,{repairId:result.repairId},false)).status).toBe(428);expect((await bootstrapKeys(a,{},false)).status).toBe(423);const repaired=await bootstrapKeys(a,{repairId:result.repairId},true);expect({status:repaired.status,body:await repaired.json()}).toEqual({status:200,body:{ok:true}});const replay=await bootstrapKeys(a,{repairId:result.repairId},true);expect({status:replay.status,body:await replay.json()}).toEqual({status:200,body:{ok:true,idempotent:true}});
  });

  test("tombstone and erasure fences precede workspace side effects",async()=>{const a=await account("g180-fence");await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(a.accountId,"rbox:genesis-repair-tombstone:v1","rbox:genesis-repair-tombstone:v1",1,"gra_"+"a".repeat(32),2).run();const ws=await SELF.fetch(`${BASE}/v1/workspaces?project=root`,{method:"POST",headers:auth(a.token)});expect(ws.status).toBe(423);expect(await ws.json()).toEqual({error:"repair_in_progress"});expect(await env.rbox_dev_db.prepare("SELECT 1 FROM workspaces WHERE account_id=?").bind(a.accountId).first()).toBeNull();
    await env.rbox_dev_db.prepare("INSERT INTO account_deletions(account_id,requested_at,purge_after,status) VALUES(?,?,?,'done')").bind(a.accountId,1,1).run();const erased=await SELF.fetch(`${BASE}/v1/workspaces?project=root`,{method:"POST",headers:auth(a.token)});expect(erased.status).toBe(410);expect(await erased.json()).toEqual({error:"account_erased"});});

  test("bootstrap 410 precedes every tombstone, repair-id, and capability response",async()=>{const a=await account("g180-erased-bootstrap"),repairId="gra_"+"b".repeat(32);await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(a.accountId,"rbox:genesis-repair-tombstone:v1","rbox:genesis-repair-tombstone:v1",1,repairId,2).run();await env.rbox_dev_db.prepare("INSERT INTO account_deletions(account_id,requested_at,purge_after,status) VALUES(?,?,?,'done')").bind(a.accountId,1,1).run();for(const [over,cap] of [[{},false],[{repairId:"gra_"+"c".repeat(32)},true],[{repairId},false],[{repairId},true]] as const){const r=await bootstrapKeys(a,over,cap);expect(r.status).toBe(410);expect(await r.json()).toEqual({error:"account_erased"});}const rows=await env.rbox_dev_db.prepare("SELECT (SELECT COUNT(*) FROM rosters WHERE account_id=?1) r,(SELECT COUNT(*) FROM device_keys WHERE account_id=?1) d").bind(a.accountId).first();expect(rows).toEqual({r:0,d:0});});

  test("all pairing-token inserts honor both erasure-ledger states, including non-E2EE",async()=>{for(const status of ["purging","done"]){const a=await account(`g180-pair-erased-${status}`);await env.rbox_dev_db.prepare("INSERT INTO account_deletions(account_id,requested_at,purge_after,status) VALUES(?,?,?,?)").bind(a.accountId,1,1,status).run();const r=await SELF.fetch(`${BASE}/v1/auth/pair/create`,{method:"POST",headers:auth(a.token,{"content-type":"application/json"}),body:"{}"});expect(r.status,status).toBe(410);expect(await r.json(),status).toEqual({error:"account_erased"});expect(await env.rbox_dev_db.prepare("SELECT 1 FROM pairing_tokens WHERE account_id=?").bind(a.accountId).first(),status).toBeNull();}});

  test("repair execute records audit=1,update=0 for every dependent-row guard",async()=>{
    const cases:Array<[string,(accountId:string)=>Promise<unknown>,string]>=[
      ["roster",id=>env.rbox_dev_db.prepare("INSERT INTO rosters(account_id,version,signed,created_at) VALUES(?,0,'r',1)").bind(id).run(),"dependent_rows"],
      ["key-state",id=>env.rbox_dev_db.prepare("INSERT INTO account_key_states(account_id,account_epoch,signed,created_at) VALUES(?,0,'k',1)").bind(id).run(),"dependent_rows"],
      ["device",id=>env.rbox_dev_db.prepare("INSERT INTO device_keys(device_id,account_id,created_at) VALUES(?,?,1)").bind(`dev_guard_${id}`,id).run(),"dependent_rows"],
      ["workspace-key",id=>env.rbox_dev_db.prepare("INSERT INTO workspace_keys(workspace_id,account_id,key_epoch,kek_wrap,created_at) VALUES(?,?,0,'k',1)").bind(`ws_key_${id}`,id).run(),"dependent_rows"],
      ["E2EE pairing token",id=>env.rbox_dev_db.prepare("INSERT INTO pairing_tokens(token_hash,account_id,user_id,created_by,created_at,expires_at,mk_wrap) VALUES(?,?,?,?,1,9999999999999,'mk')").bind(`pt_guard_${id}`,id,"user_guard","dev_guard").run(),"dependent_rows"],
      ["workspace",id=>env.rbox_dev_db.prepare("INSERT INTO workspaces(workspace_id,project_id,account_id,created_at) VALUES(?,'root',?,1)").bind(`ws_guard_${id}`,id).run(),"workspace_history"],
    ];
    for(const [label,seed,classification] of cases){
      const a=await account(`g180-guard-${label}`);await oldClaim(a.accountId);await seed(a.accountId);
      const response=await adminRepair(a.accountId);expect(response.status,label).toBe(409);
      const result=await response.json() as {auditId:string;classification:string};expect(result.classification,label).toBe("repair_refused_state_changed");
      const audit=await env.rbox_dev_db.prepare("SELECT observed_classification,outcome,result_vector FROM genesis_repair_audit WHERE audit_id=?").bind(result.auditId).first();
      expect(audit,label).toEqual({observed_classification:classification,outcome:"refused",result_vector:"audit=1,update=0"});
      const claim=await env.rbox_dev_db.prepare("SELECT recovery_wrap,repair_id FROM account_keys WHERE account_id=?").bind(a.accountId).first();
      expect(claim,label).toEqual({recovery_wrap:"legacy-wrap",repair_id:null});
    }
  });

  test("repair execute exercises every old-claim field predicate with an audited no-op",async()=>{
    const mutations:Array<[string,string,unknown,"not_found"|"malformed_claim"]>=[["absent","",null,"not_found"],["recovery-wrap","recovery_wrap",null,"malformed_claim"],["recovery-wrap-id","recovery_wrap_id","","malformed_claim"],["created-at","created_at",0,"malformed_claim"],["genesis-device","genesis_device_id","dev_old","malformed_claim"],["repair-id","repair_id",`gra_${"9".repeat(32)}`,"malformed_claim"],["repaired-at","repaired_at",2,"malformed_claim"]];
    for(const [label,column,value,classification] of mutations){const a=await account(`g180-claim-${label}`);if(label!=="absent"){await oldClaim(a.accountId);await env.rbox_dev_db.prepare(`UPDATE account_keys SET ${column}=? WHERE account_id=?`).bind(value,a.accountId).run();}const response=await adminRepair(a.accountId);expect(response.status,label).toBe(409);const envelope=await response.json() as {auditId:string;classification:string};expect(envelope.classification,label).toBe("repair_refused_state_changed");expect(await env.rbox_dev_db.prepare("SELECT observed_classification,outcome,result_vector,original_claim_snapshot FROM genesis_repair_audit WHERE audit_id=?").bind(envelope.auditId).first(),label).toMatchObject({observed_classification:classification,outcome:"refused",result_vector:"audit=1,update=0",original_claim_snapshot:expect.any(String)});}
  });

  test("a competitor completing between execute batch and re-read reconciles instead of returning 409",async()=>{
    const a=await account("g180-completed-competitor");await oldClaim(a.accountId);const competitor=`gra_${"d".repeat(32)}`;
    const response=await genesisRepair(env,a.accountId,{accountId:a.accountId,operator:"on-call@example.com",reason:"support case RBOX-180: split genesis",dryRun:false},0,{
      beforeExecuteBatch:async()=>{await env.rbox_dev_db.prepare("INSERT INTO genesis_repair_audit(audit_id,account_id,operator,reason,requested_at,dry_run,observed_classification,proof_json,outcome) VALUES(?,?,?,?,?,0,'exact_legacy_orphan','{}','attempted')").bind(competitor,a.accountId,"competitor@example.com","concurrent repair",Date.now()+10_000).run();},
      afterExecuteBatch:async()=>{await env.rbox_dev_db.batch([env.rbox_dev_db.prepare("UPDATE account_keys SET recovery_wrap=?,recovery_wrap_id=?,repair_id=?,repaired_at=3 WHERE account_id=?").bind(GENESIS_TOMBSTONE_SENTINEL,GENESIS_TOMBSTONE_SENTINEL,competitor,a.accountId),env.rbox_dev_db.prepare("UPDATE genesis_repair_audit SET outcome='tombstone_claim_installed',result_vector='audit=1,update=1',completed_at=3 WHERE audit_id=?").bind(competitor)]);},
    });
    expect(response.status).toBe(200);expect(await response.json()).toMatchObject({ok:true,repairId:competitor,result:"tombstone_claim_installed"});expect(await env.rbox_dev_db.prepare("SELECT COUNT(*) n FROM genesis_repair_audit WHERE account_id=? AND outcome='attempted'").bind(a.accountId).first()).toEqual({n:0});expect(await env.rbox_dev_db.prepare("SELECT COUNT(*) n FROM genesis_repair_audit WHERE account_id=? AND outcome='refused'").bind(a.accountId).first()).toEqual({n:2});
  });

  test("stranded repair audits reconcile deterministically before account observation",async()=>{
    const installed=await account("g180-reconcile-installed"),installedId=`gra_${"e".repeat(32)}`;
    await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(installed.accountId,"rbox:genesis-repair-tombstone:v1","rbox:genesis-repair-tombstone:v1",1,installedId,2).run();
    await env.rbox_dev_db.prepare("INSERT INTO genesis_repair_audit(audit_id,account_id,requested_at,dry_run,outcome) VALUES(?,?,1,0,'attempted')").bind(installedId,installed.accountId).run();
    expect((await SELF.fetch(`${BASE}/v1/keys/account`,{headers:auth(installed.token)})).status).toBe(200);
    expect(await env.rbox_dev_db.prepare("SELECT outcome,result_vector,completed_at FROM genesis_repair_audit WHERE audit_id=?").bind(installedId).first()).toMatchObject({outcome:"tombstone_claim_installed",result_vector:"audit=1,update=1",completed_at:expect.any(Number)});

    const refused=await account("g180-reconcile-refused"),refusedId=`gra_${"f".repeat(32)}`;await oldClaim(refused.accountId);
    await env.rbox_dev_db.prepare("INSERT INTO genesis_repair_audit(audit_id,account_id,requested_at,dry_run,outcome) VALUES(?,?,1,0,'attempted')").bind(refusedId,refused.accountId).run();
    expect((await SELF.fetch(`${BASE}/v1/keys/account`,{headers:auth(refused.token)})).status).toBe(200);
    const refusedAudit=await env.rbox_dev_db.prepare("SELECT outcome,result_vector,completion_observation_json FROM genesis_repair_audit WHERE audit_id=?").bind(refusedId).first<{outcome:string;result_vector:string;completion_observation_json:string}>();
    expect(refusedAudit).toMatchObject({outcome:"refused",result_vector:"audit=1,update=0"});expect(JSON.parse(refusedAudit!.completion_observation_json)).toMatchObject({observational:true,claimShape:"old_endpoint_exact"});
  });

  test("deletion-first reverse order refuses repair before creating an audit",async()=>{
    for(const status of ["purging","done"]){const a=await account(`g180-delete-first-${status}`);await oldClaim(a.accountId);await env.rbox_dev_db.prepare("INSERT INTO account_deletions(account_id,requested_at,purge_after,status) VALUES(?,?,?,?)").bind(a.accountId,1,1,status).run();const response=await adminRepair(a.accountId);expect(response.status,status).toBe(410);expect(await env.rbox_dev_db.prepare("SELECT COUNT(*) n FROM genesis_repair_audit WHERE account_id=?").bind(a.accountId).first(),status).toEqual({n:0});}
  });

  test("real finishD1 wins before repair, ordinary/repair bootstrap, and workspace batches",async()=>{
    for(const [branchIndex,branch] of (["execute","dry-run","ordinary-bootstrap","repair-bootstrap","workspace"] as const).entries()){const a=await account(`g180-finish-first-${branch}`),repairId=`gra_c${branchIndex.toString(16)}${"0".repeat(30)}`;if(branch==="execute"||branch==="dry-run")await oldClaim(a.accountId);if(branch==="repair-bootstrap")await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(a.accountId,GENESIS_TOMBSTONE_SENTINEL,GENESIS_TOMBSTONE_SENTINEL,1,repairId,2).run();await env.rbox_dev_db.prepare("INSERT INTO account_deletions(account_id,requested_at,purge_after,status) VALUES(?,?,?,'purging')").bind(a.accountId,1,1).run();await finishD1(env,a.accountId,[],[],3);const principal={accountId:a.accountId,deviceId:a.deviceId,userId:"user_finish",role:"owner"} as const;let response:Response;if(branch==="execute"||branch==="dry-run")response=await genesisRepair(env,a.accountId,{accountId:a.accountId,operator:"on-call@example.com",reason:"finishD1 reverse race",dryRun:branch==="dry-run"});else if(branch==="workspace")response=await createWorkspace(env,principal as never,"root");else response=await bootstrapAccountKeys(env,principal as never,body(a.deviceId,branch==="repair-bootstrap"?repairId:undefined),"1");expect(response.status,branch).toBe(410);const envelope=await response.json() as {error?:string;classification?:string;result?:string;dryRun?:boolean;auditId?:string};if(branch==="execute"||branch==="dry-run"){expect(envelope,branch).toMatchObject({classification:"account_erased",result:"refused",dryRun:branch==="dry-run"});expect(envelope).not.toHaveProperty("auditId");}else expect(envelope,branch).toMatchObject({error:"account_erased"});expect(await env.rbox_dev_db.prepare("SELECT (SELECT COUNT(*) FROM account_keys WHERE account_id=?1) a,(SELECT COUNT(*) FROM rosters WHERE account_id=?1) r,(SELECT COUNT(*) FROM account_key_states WHERE account_id=?1) k,(SELECT COUNT(*) FROM device_keys WHERE account_id=?1) d,(SELECT COUNT(*) FROM workspaces WHERE account_id=?1) w,(SELECT COUNT(*) FROM genesis_repair_audit WHERE account_id=?1) g").bind(a.accountId).first(),branch).toEqual({a:0,r:0,k:0,d:0,w:0,g:0});}
  });

  test("workspace manifest and receipt writes fence tombstone and erasure before DO forwarding",async()=>{
    const a=await account("g180-sync-fence");const created=await SELF.fetch(`${BASE}/v1/workspaces?project=root`,{method:"POST",headers:auth(a.token)});expect(created.status).toBe(200);const {workspaceId}=await created.json() as {workspaceId:string};
    const repairId=`gra_${"1".repeat(32)}`;await env.rbox_dev_db.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(a.accountId,"rbox:genesis-repair-tombstone:v1","rbox:genesis-repair-tombstone:v1",1,repairId,2).run();
    const manifestUrl=`${BASE}/v1/ws/${workspaceId}/proj/root/manifests`,receiptUrl=`${BASE}/v1/ws/${workspaceId}/proj/root/receipts/redeem`;
    for(const url of [manifestUrl,receiptUrl]){const response=await SELF.fetch(url,{method:"POST",headers:auth(a.token,{"content-type":"application/json"}),body:"{}"});expect(response.status,url).toBe(423);expect(await response.json()).toEqual({error:"repair_in_progress"});}
    await env.rbox_dev_db.prepare("INSERT INTO account_deletions(account_id,requested_at,purge_after,status) VALUES(?,?,?,'purging')").bind(a.accountId,1,1).run();
    for(const url of [manifestUrl,receiptUrl]){const response=await SELF.fetch(url,{method:"POST",headers:auth(a.token,{"content-type":"application/json"}),body:"{}"});expect(response.status,url).toBe(410);expect(await response.json()).toEqual({error:"account_erased"});}
  });

  test("workspace write fence observes a tombstone injected at the immediate pre-DO-forwarding query",async()=>{
    for(const path of ["manifests","receipts/redeem"]){
      const a=await account(`g180-sync-injected-${path.replace("/","-")}`);const principal={accountId:a.accountId,deviceId:a.deviceId,userId:"user_injected",role:"owner",kind:"device"} as const;
      const created=await createWorkspace(env,principal,"root");expect(created.status,path).toBe(200);const {workspaceId}=await created.json() as {workspaceId:string};
      let injected=0,forwarded=0;const repairId=`gra_e${path.startsWith("manifests")?"0":"1"}${"0".repeat(30)}`,realDb=env.rbox_dev_db;
      const injectedDb={prepare(sql:string){const statement=realDb.prepare(sql);if(!sql.includes("SELECT 1 FROM account_keys WHERE account_id = ? AND"))return statement;return {bind(...values:unknown[]){const bound=statement.bind(...values);return {first:async()=>{injected++;await realDb.prepare("INSERT INTO account_keys(account_id,recovery_wrap,recovery_wrap_id,created_at,repair_id,repaired_at) VALUES(?,?,?,?,?,?)").bind(a.accountId,GENESIS_TOMBSTONE_SENTINEL,GENESIS_TOMBSTONE_SENTINEL,1,repairId,2).run();return bound.first();}} as D1PreparedStatement;}} as D1PreparedStatement;}} as D1Database;
      const testEnv={...env,rbox_dev_db:injectedDb,WORKSPACE_SYNC:{idFromName:(_name:string)=>({}) as DurableObjectId,get:(_id:DurableObjectId)=>({fetch:async(_input:string|Request,_init?:RequestInit)=>{forwarded++;return Response.json({ok:true});}} as DurableObjectStub)} as DurableObjectNamespace};
      const url=new URL(`${BASE}/v1/ws/${workspaceId}/proj/root/${path}`),request=new Request(url,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});
      const response=await syncRoutes({req:request,env:testEnv,exports:{} as never,executionCtx:{waitUntil:()=>{}},url,seg:url.pathname.split("/").filter(Boolean)},principal);
      expect(injected,path).toBe(1);expect(response?.status,path).toBe(423);expect(await response!.json(),path).toEqual({error:"repair_in_progress"});expect(forwarded,path).toBe(0);
    }
  });

  test("account observation returns arrays coherent with the same batch's presence counts",async()=>{
    const a=await account("g180-coherent-get");expect((await bootstrapKeys(a)).status).toBe(200);
    await env.rbox_dev_db.batch([
      env.rbox_dev_db.prepare("INSERT INTO rosters(account_id,version,signed,created_at) VALUES(?,1,'roster-v1',2)").bind(a.accountId),
      env.rbox_dev_db.prepare("INSERT INTO account_key_states(account_id,account_epoch,signed,created_at) VALUES(?,1,'keystate-1',2)").bind(a.accountId),
      env.rbox_dev_db.prepare("INSERT INTO device_keys(device_id,account_id,sig_pubkey,enc_pubkey,mk_wrap,created_at) VALUES(?,?,?,?,?,2)").bind(`dev_coherent_${a.accountId}`,a.accountId,"sig2","enc2","mk2"),
    ]);
    const response=await SELF.fetch(`${BASE}/v1/keys/account`,{headers:auth(a.token)});expect(response.status).toBe(200);const observed=await response.json() as {rosters:unknown[];keyStates:unknown[];devices:unknown[];present:{rosters:number;keyStates:number;devices:number}};
    expect(observed.present.rosters).toBe(observed.rosters.length);expect(observed.present.keyStates).toBe(observed.keyStates.length);expect(observed.present.devices).toBe(observed.devices.length);expect(observed.present).toMatchObject({rosters:2,keyStates:2,devices:2});
  });

  test("concurrent repair/workspace fencing and bootstrap observations serialize to coherent sides",async()=>{
    const fenced=await account("g180-fence-race");await oldClaim(fenced.accountId);const principal={accountId:fenced.accountId,deviceId:fenced.deviceId,userId:"user_race",role:"owner"} as const,[repair,workspace]=await Promise.all([genesisRepair(env,fenced.accountId,{accountId:fenced.accountId,operator:"on-call@example.com",reason:"workspace fence race",dryRun:false}),createWorkspace(env,principal as never,"root")]);expect([repair.status,workspace.status].filter(status=>status===200)).toHaveLength(1);const raced=await env.rbox_dev_db.prepare("SELECT (SELECT COUNT(*) FROM workspaces WHERE account_id=?1) w,(SELECT COUNT(*) FROM account_keys WHERE account_id=?1 AND repair_id IS NOT NULL) t").bind(fenced.accountId).first<{w:number;t:number}>();expect(raced!.w+raced!.t).toBe(1);
    for(let i=0;i<8;i++){const a=await account(`g180-observe-race-${i}`),p={accountId:a.accountId,deviceId:a.deviceId} as never,[observed,published]=await Promise.all([getAccountKeys(env,p),bootstrapAccountKeys(env,p,body(a.deviceId),"1")]);expect(published.status).toBe(200);if(observed.status===404)expect(await observed.json()).toMatchObject({present:{rosters:0,keyStates:0,devices:0}});else{expect(observed.status).toBe(200);const dto=await observed.json() as {rosters:unknown[];keyStates:unknown[];devices:unknown[];present:{rosters:number;keyStates:number;devices:number}};expect(dto.present).toMatchObject({rosters:dto.rosters.length,keyStates:dto.keyStates.length,devices:dto.devices.length});}}
  });
});
